/**
 * V80 Pilot P8 — Built-in enterprise knowledge refs + compliance rules (deterministic)
 */

import type { ComplianceRule, KnowledgeReference } from "./compliance.schema";

export const DEFAULT_KNOWLEDGE_REFERENCES: KnowledgeReference[] = [
  {
    id: "kr-gb-t-22517",
    domain: "standards",
    title: "体育场地要求 第4部分：健身场地",
    code: "GB/T 22517.4",
    summary: "健身场地安全与设施布置相关国家标准参考。",
    keywords: ["GB/T 22517", "22517", "健身场地", "体育场地"],
    mandatoryHint: true,
  },
  {
    id: "kr-gb-17498",
    domain: "standards",
    title: "固定式健身器材安全通用要求",
    code: "GB 17498",
    summary: "固定式健身器材安全与标识要求。",
    keywords: ["GB 17498", "17498", "健身器材", "安全通用"],
    mandatoryHint: true,
  },
  {
    id: "kr-iso-20957",
    domain: "standards",
    title: "Stationary training equipment",
    code: "ISO 20957",
    summary: "固定训练器械国际标准参考。",
    keywords: ["ISO 20957", "20957", "training equipment"],
  },
  {
    id: "kr-ccc",
    domain: "certification",
    title: "强制性产品认证（如适用）",
    code: "CCC",
    summary: "电气类设备可能需要 3C/CCC 认证。",
    keywords: ["CCC", "3C", "认证", "强制认证"],
  },
  {
    id: "kr-iso-9001",
    domain: "certification",
    title: "质量管理体系",
    code: "ISO 9001",
    summary: "常见投标资质认证参考。",
    keywords: ["ISO 9001", "质量体系", "质量管理"],
  },
  {
    id: "kr-safety-clearance",
    domain: "safety",
    title: "器械安全间距与防护",
    summary: "有氧/力量区应保留安全间距与防护措施。",
    keywords: ["安全间距", "防护", "急停", "安全"],
    mandatoryHint: true,
  },
  {
    id: "kr-space-area",
    domain: "space",
    title: "健身场地面积与分区",
    summary: "应明确建筑面积或使用面积及功能分区。",
    keywords: ["面积", "㎡", "平方米", "分区", "有氧区", "力量区"],
  },
  {
    id: "kr-equipment-qty",
    domain: "equipment",
    title: "设备数量与品牌规格",
    summary: "设备条目应含数量与关键规格。",
    keywords: ["台", "套", "数量", "不少于"],
  },
  {
    id: "kr-budget-band",
    domain: "commercial",
    title: "预算/限价信息",
    summary: "建议明确预算区间或限价，便于方案与报价对齐。",
    keywords: ["预算", "限价", "金额"],
  },
];

export const DEFAULT_COMPLIANCE_RULES: ComplianceRule[] = [
  {
    id: "rule-project-basics",
    category: "completeness",
    severity: "blocking",
    title: "项目基础信息完整",
    description: "项目名称、招标单位、地点必须齐全。",
    matcher: "require_project_basics",
  },
  {
    id: "rule-tech-or-func",
    category: "completeness",
    severity: "blocking",
    title: "技术/功能需求存在",
    description: "至少一条技术或功能需求。",
    matcher: "require_tech_or_func",
  },
  {
    id: "rule-standard-mention",
    category: "standards",
    severity: "blocking",
    title: "健身场景需引用标准",
    description: "检测到健身/器械场景时，应引用 GB/T 22517 或 GB 17498 等标准。",
    knowledgeRefIds: ["kr-gb-t-22517", "kr-gb-17498"],
    matcher: "require_standard_mention",
  },
  {
    id: "rule-cert-when-compliance",
    category: "certification",
    severity: "warning",
    title: "合规条目需认证线索",
    description: "存在合规/资质条目时，建议包含 ISO/CCC 等认证要求。",
    knowledgeRefIds: ["kr-iso-9001", "kr-ccc"],
    matcher: "require_certification_when_compliance",
  },
  {
    id: "rule-ambiguous-qty",
    category: "consistency",
    severity: "blocking",
    title: "数量表述不可含糊",
    description: "设备/数量条目不得使用「大约/若干/待定」等含糊词。",
    knowledgeRefIds: ["kr-equipment-qty"],
    matcher: "flag_ambiguous_quantity",
  },
  {
    id: "rule-missing-budget",
    category: "commercial",
    severity: "warning",
    title: "预算信息缺失",
    description: "缺少预算上下限或说明。",
    knowledgeRefIds: ["kr-budget-band"],
    matcher: "flag_missing_budget",
  },
  {
    id: "rule-space-area",
    category: "completeness",
    severity: "warning",
    title: "空间条目缺面积",
    description: "存在空间/场地需求但未给出面积数字。",
    knowledgeRefIds: ["kr-space-area"],
    matcher: "flag_space_without_area",
  },
  {
    id: "rule-equipment-safety",
    category: "safety",
    severity: "warning",
    title: "设备需求缺安全表述",
    description: "有设备条目时，建议补充安全间距/防护/急停等要求。",
    knowledgeRefIds: ["kr-safety-clearance"],
    matcher: "flag_equipment_without_safety",
  },
  {
    id: "rule-budget-scope",
    category: "consistency",
    severity: "info",
    title: "预算与范围一致性提示",
    description: "高额预算但范围过短时给出提示。",
    matcher: "consistency_budget_vs_scope",
  },
  {
    id: "rule-location-fitness",
    category: "completeness",
    severity: "warning",
    title: "健身项目应明确地点",
    description: "健身相关项目缺少地点时提示补全。",
    matcher: "require_location_for_fitness",
  },
];
