import type { SaasSystemRoleDefinition } from "../shared/types";

export const SAAS_SYSTEM_ROLES: SaasSystemRoleDefinition[] = [
  {
    systemCode: "enterprise_owner",
    name: "Enterprise Owner",
    scope: "tenant",
    portalType: "enterprise",
    permissionKeys: [
      "quote:create",
      "quote:read",
      "approval:submit",
      "approval:approve",
      "package:download",
      "delivery:execute",
      "audit:read",
      "release:publish",
      "workspace:manage",
      "member:invite",
      "member:remove",
      "tenant:admin",
      "billing:read",
      "subscription:read",
    ],
  },
  {
    systemCode: "enterprise_admin",
    name: "Enterprise Admin",
    scope: "organization",
    portalType: "enterprise",
    permissionKeys: [
      "quote:create",
      "quote:read",
      "approval:submit",
      "approval:approve",
      "package:download",
      "delivery:execute",
      "audit:read",
      "workspace:manage",
      "member:invite",
      "member:remove",
      "billing:read",
      "subscription:read",
    ],
  },
  {
    systemCode: "enterprise_sales",
    name: "Enterprise Sales",
    scope: "workspace",
    portalType: "enterprise",
    permissionKeys: ["quote:create", "quote:read", "approval:submit", "package:download", "subscription:read"],
  },
  {
    systemCode: "contractor_owner",
    name: "Contractor Owner",
    scope: "tenant",
    portalType: "contractor",
    permissionKeys: [
      "quote:create",
      "quote:read",
      "approval:submit",
      "approval:approve",
      "package:download",
      "delivery:execute",
      "audit:read",
      "workspace:manage",
      "member:invite",
      "member:remove",
      "tenant:admin",
      "billing:read",
      "subscription:read",
    ],
  },
  {
    systemCode: "contractor_pm",
    name: "Contractor PM",
    scope: "workspace",
    portalType: "contractor",
    permissionKeys: [
      "quote:read",
      "approval:submit",
      "approval:approve",
      "package:download",
      "delivery:execute",
      "audit:read",
      "workspace:manage",
      "member:invite",
    ],
  },
  {
    systemCode: "contractor_estimator",
    name: "Contractor Estimator",
    scope: "workspace",
    portalType: "contractor",
    permissionKeys: ["quote:create", "quote:read", "package:download", "delivery:execute"],
  },
  {
    systemCode: "supplier_admin",
    name: "Supplier Admin",
    scope: "organization",
    portalType: "supplier",
    permissionKeys: [
      "supplier.catalog:read",
      "quote:read",
      "workspace:manage",
      "member:invite",
      "member:remove",
      "tenant:admin",
      "subscription:read",
    ],
  },
  {
    systemCode: "supplier_rep",
    name: "Supplier Rep",
    scope: "workspace",
    portalType: "supplier",
    permissionKeys: ["supplier.catalog:read", "quote:read"],
  },
  {
    systemCode: "manufacturer_admin",
    name: "Manufacturer Admin",
    scope: "organization",
    portalType: "manufacturer",
    permissionKeys: [
      "manufacturer.brand:read",
      "workspace:manage",
      "member:invite",
      "member:remove",
      "tenant:admin",
      "subscription:read",
    ],
  },
  {
    systemCode: "manufacturer_sku_manager",
    name: "Manufacturer SKU Manager",
    scope: "workspace",
    portalType: "manufacturer",
    permissionKeys: ["manufacturer.brand:read", "supplier.catalog:read"],
  },
];

export function getSystemRoleByCode(systemCode: string): SaasSystemRoleDefinition | undefined {
  return SAAS_SYSTEM_ROLES.find((role) => role.systemCode === systemCode);
}
