/**
 * Plan 正文 / 目录 — V1 Commercial Freeze 别名层
 */
export type { PlanBodyLineKind } from "@/lib/pdf/planTypography.body";
export {
  planBodyDrawX,
  planBodyFontSize,
  planBodyLineAdvance,
  planClassifyBodyLine,
} from "@/lib/pdf/planTypography.body";

import {
  FREEZE_BODY_BOTTOM,
  FREEZE_BODY_SIZE,
  FREEZE_BODY_TOP,
  FREEZE_CALLOUT_INDENT,
  FREEZE_CHAPTER_NUM_SIZE,
  FREEZE_DELIVERY_NOTICE_PAGE_INDEX,
  FREEZE_DIVIDER_WIDTH_RATIO,
  FREEZE_LINE_HEIGHT,
  FREEZE_LIST_INDENT,
  FREEZE_MARGIN_X,
  FREEZE_PAGE_HEIGHT,
  FREEZE_PAGE_WIDTH,
  FREEZE_SUBLIST_INDENT,
  FREEZE_TITLE_BOTTOM_SPACING,
  FREEZE_TITLE_GAP_AFTER_EN,
  FREEZE_TITLE_GAP_AFTER_NUM,
  FREEZE_TITLE_GAP_ZH_TO_EN,
  FREEZE_TITLE_TOP_SPACING,
  FREEZE_TITLE_TOP_SPACING_CONT,
  FREEZE_TOC_LEADER_GAP,
  FREEZE_TOC_ROW_STEP,
  freezeBodyStartPage1Based,
  freezeFrontMatterPageCount,
} from "@/lib/pdf/commercialFreezeDesignSystem";

export const PLAN_PAGE_WIDTH = FREEZE_PAGE_WIDTH;
export const PLAN_PAGE_HEIGHT = FREEZE_PAGE_HEIGHT;
export const PLAN_MARGIN_X = FREEZE_MARGIN_X;
export const PLAN_BODY_TOP = FREEZE_BODY_TOP;
export const PLAN_BODY_BOTTOM = FREEZE_BODY_BOTTOM;
export const PLAN_BODY_SIZE = FREEZE_BODY_SIZE;
export const PLAN_LINE_HEIGHT = FREEZE_LINE_HEIGHT;
export const PLAN_TOC_ROW_STEP = FREEZE_TOC_ROW_STEP;
export const PLAN_TOC_LEADER_GAP = FREEZE_TOC_LEADER_GAP;
export const PLAN_TITLE_TOP_SPACING = FREEZE_TITLE_TOP_SPACING;
export const PLAN_TITLE_TOP_SPACING_CONT = FREEZE_TITLE_TOP_SPACING_CONT;
export const PLAN_CHAPTER_NUM_SIZE = FREEZE_CHAPTER_NUM_SIZE;
export const PLAN_TITLE_GAP_AFTER_BIG_NUM = FREEZE_TITLE_GAP_AFTER_NUM;
export const PLAN_TITLE_GAP_ZH_TO_EN = FREEZE_TITLE_GAP_ZH_TO_EN;
export const PLAN_TITLE_GAP_AFTER_EN = FREEZE_TITLE_GAP_AFTER_EN;
export const PLAN_TITLE_BOTTOM_SPACING = FREEZE_TITLE_BOTTOM_SPACING;
export const PLAN_CHAPTER_DIVIDER_WIDTH_RATIO = FREEZE_DIVIDER_WIDTH_RATIO;
export const PLAN_LIST_INDENT = FREEZE_LIST_INDENT;
export const PLAN_SUBLIST_INDENT = FREEZE_SUBLIST_INDENT;
export const PLAN_CALLOUT_INDENT = FREEZE_CALLOUT_INDENT;
export const PLAN_DELIVERY_NOTICE_PAGE_INDEX = FREEZE_DELIVERY_NOTICE_PAGE_INDEX;

export const planFrontMatterPageCount = freezeFrontMatterPageCount;
export const planBodyStartPage1Based = freezeBodyStartPage1Based;
