/**
 * PI-3.4 — Action → existing API surface bindings (PD-2.4 / PD-5.3).
 * Closed 47-row map. No new routes or families.
 */
import type { ApiFamilyId } from "./api-families";
import type { RuntimeSurfaceId } from "../runtime/runtime-surfaces";

export const API_BINDING_SOURCE_ID = "product-planning-pd-2.4-v1" as const;

export type ApiBindingKind = "API" | "API+NAV" | "NEAREST" | "NAV" | "PREF";

export type ApiSurfaceBinding = Readonly<{
  actionId: string;
  command: string;
  bindingKind: ApiBindingKind;
  /** Existing routes (preferred first). Empty for NAV/PREF. */
  routes: readonly string[];
  families: readonly ApiFamilyId[];
  surfaces: readonly RuntimeSurfaceId[];
  notes: string;
}>;

/**
 * PD-2.4 Action → Command → Existing API map (47).
 */
export const API_SURFACE_BINDINGS = [
  {
    actionId: "ACT-01-01",
    command: "SignIn",
    bindingKind: "API",
    routes: [
      "/api/auth/otp/request",
      "/api/auth/otp/verify",
      "/api/auth/email/request",
      "/api/auth/me",
    ],
    families: ["FAM-AUTH"],
    surfaces: ["DOM-AUTH"],
    notes: "Existing auth only",
  },
  {
    actionId: "ACT-01-02",
    command: "SelectLanguage",
    bindingKind: "PREF",
    routes: [],
    families: [],
    surfaces: ["DOM-PREF"],
    notes: "Client preference; no HTTP product API",
  },
  {
    actionId: "ACT-01-03",
    command: "ChooseGoal.EnterpriseBuilder",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigation to SCR-02",
  },
  {
    actionId: "ACT-01-04",
    command: "ChooseGoal.TenderIntelligence",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigation to SCR-03",
  },
  {
    actionId: "ACT-01-05",
    command: "ChooseGoal.SalesCenter",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigation to SCR-04",
  },
  {
    actionId: "ACT-01-06",
    command: "OpenMyProjects",
    bindingKind: "API+NAV",
    routes: ["/api/project/list"],
    families: ["FAM-PROJECT"],
    surfaces: ["DOM-PROJECT"],
    notes: "Then navigate SCR-07",
  },
  {
    actionId: "ACT-02-01",
    command: "StartPlanning",
    bindingKind: "NEAREST",
    routes: ["/api/v80/tenant/run", "/api/onboarding/submit"],
    families: ["FAM-V80", "FAM-PLAN"],
    surfaces: ["DOM-TENANT", "DOM-PLAN"],
    notes: "Nearest planning bootstrap",
  },
  {
    actionId: "ACT-02-02",
    command: "SubmitPlanningInputs",
    bindingKind: "NEAREST",
    routes: ["/api/v80/budget/calculate", "/api/plan"],
    families: ["FAM-V80", "FAM-PLAN"],
    surfaces: ["DOM-BUDGET", "DOM-PLAN"],
    notes: "Inputs feed existing budget/plan surfaces",
  },
  {
    actionId: "ACT-02-03",
    command: "ContinueToWorkspace",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigate SCR-04",
  },
  {
    actionId: "ACT-03-01",
    command: "UploadTenderDocument",
    bindingKind: "API",
    routes: ["/api/v80/tender/intake", "/api/tender/intake"],
    families: ["FAM-V80", "FAM-TENDER"],
    surfaces: ["DOM-TENDER"],
    notes: "Preferred v80; legacy secondary",
  },
  {
    actionId: "ACT-03-02",
    command: "ViewProcessingStatus",
    bindingKind: "API",
    routes: [
      "/api/v80/tender/intake",
      "/api/tender/[projectId]",
      "/api/tender/gate",
    ],
    families: ["FAM-V80", "FAM-TENDER"],
    surfaces: ["DOM-TENDER"],
    notes: "Existing status surfaces only",
  },
  {
    actionId: "ACT-03-03",
    command: "ProceedToRequirementReview",
    bindingKind: "API+NAV",
    routes: ["/api/tender/analyze"],
    families: ["FAM-TENDER"],
    surfaces: ["DOM-TENDER"],
    notes: "Nearest tender analyze; then SCR-04",
  },
  {
    actionId: "ACT-04-01",
    command: "WorkspaceInteract",
    bindingKind: "NEAREST",
    routes: ["/api/workspace/summary", "/api/v80/autopilot/job/run"],
    families: ["FAM-WORKSPACE", "FAM-V80"],
    surfaces: ["DOM-PROJECT", "DOM-AUTOPILOT"],
    notes: "No dedicated chat API",
  },
  {
    actionId: "ACT-04-02",
    command: "ViewProjectContext",
    bindingKind: "API",
    routes: ["/api/project/[projectId]", "/api/workspace/summary"],
    families: ["FAM-PROJECT", "FAM-WORKSPACE"],
    surfaces: ["DOM-PROJECT"],
    notes: "Existing project context",
  },
  {
    actionId: "ACT-04-03",
    command: "ConfirmRequirements",
    bindingKind: "NEAREST",
    routes: ["/api/tender/analyze", "/api/tender/gate"],
    families: ["FAM-TENDER"],
    surfaces: ["DOM-TENDER"],
    notes: "Existing tender review surfaces",
  },
  {
    actionId: "ACT-04-04",
    command: "GenerateTenderPackage",
    bindingKind: "API",
    routes: ["/api/v80/autopilot/job/run"],
    families: ["FAM-V80"],
    surfaces: ["DOM-AUTOPILOT", "DOM-TENDER"],
    notes: "tender-pack-complete journey",
  },
  {
    actionId: "ACT-04-05",
    command: "CaptureOpportunity",
    bindingKind: "NEAREST",
    routes: ["/api/sales/signals", "/api/sales/analyze"],
    families: ["FAM-SALES"],
    surfaces: ["DOM-SALES"],
    notes: "Existing sales surfaces only",
  },
  {
    actionId: "ACT-04-06",
    command: "OpenSolutionResult",
    bindingKind: "API+NAV",
    routes: ["/api/v80/pdf?type=plan", "/api/v80/proposal-pdf/render"],
    families: ["FAM-PDF"],
    surfaces: ["DOM-PDF", "DOM-PROPOSAL"],
    notes: "Then navigate SCR-05",
  },
  {
    actionId: "ACT-04-07",
    command: "OpenBudgetResult",
    bindingKind: "API+NAV",
    routes: ["/api/v80/budget/calculate"],
    families: ["FAM-V80"],
    surfaces: ["DOM-BUDGET"],
    notes: "Then navigate SCR-06",
  },
  {
    actionId: "ACT-04-08",
    command: "OpenDocuments",
    bindingKind: "API+NAV",
    routes: ["/api/documents/projects/[projectId]"],
    families: ["FAM-DOCUMENTS"],
    surfaces: ["DOM-DOCS"],
    notes: "Then navigate SCR-08",
  },
  {
    actionId: "ACT-05-01",
    command: "ReviewSolution",
    bindingKind: "API",
    routes: ["/api/v80/pdf?type=plan"],
    families: ["FAM-PDF"],
    surfaces: ["DOM-PDF", "DOM-PROPOSAL"],
    notes: "Review existing plan artifact",
  },
  {
    actionId: "ACT-05-02",
    command: "ReviewProposalResult",
    bindingKind: "API",
    routes: [
      "/api/v80/proposal-pdf/render",
      "/api/v80/pdf?artifactId=",
    ],
    families: ["FAM-PDF"],
    surfaces: ["DOM-PDF", "DOM-PROPOSAL"],
    notes: "Existing proposal/pack results (autopilot artifacts via pdf)",
  },
  {
    actionId: "ACT-05-03",
    command: "DownloadSolution",
    bindingKind: "API",
    routes: ["/api/v80/pdf?artifactId=", "/api/v80/pdf?type=plan"],
    families: ["FAM-PDF"],
    surfaces: ["DOM-PDF"],
    notes: "Preferred download surface",
  },
  {
    actionId: "ACT-05-04",
    command: "ShareSolution",
    bindingKind: "NEAREST",
    routes: [
      "/api/download-token",
      "/api/commercial-delivery/download/run",
    ],
    families: ["FAM-DOWNLOAD"],
    surfaces: ["DOM-DOCS"],
    notes: "Nearest delivery/token surface",
  },
  {
    actionId: "ACT-05-05",
    command: "ContinueToBudget",
    bindingKind: "API+NAV",
    routes: ["/api/v80/budget/calculate"],
    families: ["FAM-V80"],
    surfaces: ["DOM-BUDGET"],
    notes: "Then navigate SCR-06",
  },
  {
    actionId: "ACT-05-06",
    command: "OpenDocuments",
    bindingKind: "API+NAV",
    routes: ["/api/documents/summary"],
    families: ["FAM-DOCUMENTS"],
    surfaces: ["DOM-DOCS"],
    notes: "Navigate SCR-08",
  },
  {
    actionId: "ACT-05-07",
    command: "ReturnToWorkspace",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigate SCR-04",
  },
  {
    actionId: "ACT-06-01",
    command: "ReviewBudget",
    bindingKind: "API",
    routes: [
      "/api/v80/budget/calculate",
      "/api/v80/pdf?type=budget",
    ],
    families: ["FAM-V80", "FAM-PDF"],
    surfaces: ["DOM-BUDGET", "DOM-PDF"],
    notes: "Existing budget result surfaces",
  },
  {
    actionId: "ACT-06-02",
    command: "DownloadBudget",
    bindingKind: "API",
    routes: ["/api/v80/pdf?type=budget"],
    families: ["FAM-PDF"],
    surfaces: ["DOM-PDF"],
    notes: "Budget artifact download",
  },
  {
    actionId: "ACT-06-03",
    command: "AdjustRequirements",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigate SCR-04",
  },
  {
    actionId: "ACT-06-04",
    command: "OpenDocuments",
    bindingKind: "API+NAV",
    routes: ["/api/documents/projects/[projectId]"],
    families: ["FAM-DOCUMENTS"],
    surfaces: ["DOM-DOCS"],
    notes: "Navigate SCR-08",
  },
  {
    actionId: "ACT-06-05",
    command: "ReturnToSolution",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigate SCR-05",
  },
  {
    actionId: "ACT-07-01",
    command: "ListProjects",
    bindingKind: "API",
    routes: ["/api/project/list"],
    families: ["FAM-PROJECT"],
    surfaces: ["DOM-PROJECT"],
    notes: "Project list",
  },
  {
    actionId: "ACT-07-02",
    command: "ContinueProject",
    bindingKind: "API+NAV",
    routes: ["/api/project/[projectId]"],
    families: ["FAM-PROJECT"],
    surfaces: ["DOM-PROJECT"],
    notes: "Then navigate SCR-04",
  },
  {
    actionId: "ACT-07-03",
    command: "OpenProjectDocuments",
    bindingKind: "API+NAV",
    routes: ["/api/documents/projects/[projectId]"],
    families: ["FAM-DOCUMENTS"],
    surfaces: ["DOM-DOCS"],
    notes: "Then navigate SCR-08",
  },
  {
    actionId: "ACT-08-01",
    command: "BrowseDocumentCategories",
    bindingKind: "API",
    routes: ["/api/documents/summary", "/api/documents/reports"],
    families: ["FAM-DOCUMENTS"],
    surfaces: ["DOM-DOCS"],
    notes: "Document categories",
  },
  {
    actionId: "ACT-08-02",
    command: "PreviewDocument",
    bindingKind: "API",
    routes: ["/api/v80/pdf?artifactId="],
    families: ["FAM-PDF"],
    surfaces: ["DOM-PDF"],
    notes: "Preview via existing PDF surface",
  },
  {
    actionId: "ACT-08-03",
    command: "DownloadDocument",
    bindingKind: "API",
    routes: [
      "/api/v80/pdf?artifactId=",
      "/api/commercial-delivery/download/run",
    ],
    families: ["FAM-PDF", "FAM-DOWNLOAD"],
    surfaces: ["DOM-PDF", "DOM-DOCS"],
    notes: "Preferred pdf; delivery secondary",
  },
  {
    actionId: "ACT-08-04",
    command: "ShareDocument",
    bindingKind: "NEAREST",
    routes: [
      "/api/download-token",
      "/api/commercial-delivery/download/run",
    ],
    families: ["FAM-DOWNLOAD"],
    surfaces: ["DOM-DOCS"],
    notes: "Same nearest binding as ShareSolution",
  },
  {
    actionId: "ACT-08-05",
    command: "ReturnToProjects",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigate SCR-07",
  },
  {
    actionId: "ACT-08-06",
    command: "ReturnToWorkspace",
    bindingKind: "NAV",
    routes: [],
    families: [],
    surfaces: [],
    notes: "Navigate SCR-04",
  },
  {
    actionId: "ACT-09-01",
    command: "ViewAdminDashboard",
    bindingKind: "API",
    routes: ["/api/enterprise-saas/dashboard/run"],
    families: ["FAM-OPS"],
    surfaces: ["DOM-OPS"],
    notes: "Existing enterprise-saas dashboard",
  },
  {
    actionId: "ACT-09-02",
    command: "ViewOrganizations",
    bindingKind: "API",
    routes: ["/api/enterprise-saas/tenant/run"],
    families: ["FAM-OPS"],
    surfaces: ["DOM-TENANT", "DOM-OPS"],
    notes: "Existing tenant surface",
  },
  {
    actionId: "ACT-09-03",
    command: "ViewUsers",
    bindingKind: "API",
    routes: ["/api/enterprise-saas/user/run"],
    families: ["FAM-OPS"],
    surfaces: ["DOM-OPS"],
    notes: "Existing user ops surface",
  },
  {
    actionId: "ACT-09-04",
    command: "ViewUsage",
    bindingKind: "API",
    routes: [
      "/api/enterprise-saas/usage/run",
      "/api/v80/ops/metrics",
    ],
    families: ["FAM-OPS"],
    surfaces: ["DOM-OPS"],
    notes: "Usage + v80 metrics",
  },
  {
    actionId: "ACT-09-05",
    command: "ViewSecurity",
    bindingKind: "NEAREST",
    routes: [
      "/api/enterprise-saas/permission/run",
      "/api/enterprise-saas/role/run",
      "/api/auth/me",
    ],
    families: ["FAM-OPS", "FAM-AUTH"],
    surfaces: ["DOM-OPS", "DOM-AUTH"],
    notes: "No dedicated security dashboard API",
  },
  {
    actionId: "ACT-09-06",
    command: "ViewGovernance",
    bindingKind: "API",
    routes: [
      "/api/v80/ops/governance/audit",
      "/api/v80/production/integrity",
    ],
    families: ["FAM-OPS"],
    surfaces: ["DOM-OPS"],
    notes: "Preferred v80 governance",
  },
] as const satisfies readonly ApiSurfaceBinding[];

export function getApiSurfaceBinding(
  actionId: string,
): ApiSurfaceBinding | undefined {
  return API_SURFACE_BINDINGS.find((row) => row.actionId === actionId);
}

export function requiresHttpExposure(kind: ApiBindingKind): boolean {
  return kind === "API" || kind === "API+NAV" || kind === "NEAREST";
}
