export * from "./shared/portal-constants";
export * from "./shared/portal-types";
export * from "./shared/portal-errors";
export { SaasProductApiClient, createSaasProductApiClient } from "./client/saas-product-api-client";
export { usePortalSession } from "./session/use-portal-session";
export { requirePortalSession, requirePortalSessionServer } from "./session/require-portal-session";
export { getPortalSessionHeaders } from "./session/get-portal-session-headers";
export { fetchPortalSessionViaMeAction } from "./session/fetch-portal-session-action";
export { resolveSessionUserFromCookieOrHeaders } from "./session/resolve-cookie-session-user";
export { PortalShell } from "./layout/portal-shell";
export { buildProductPortalNavigation } from "./layout/portal-navigation";
export { MOCK_PORTAL_KPI } from "./hooks/use-portal-kpi";
export { DashboardKpiCards } from "./components/dashboard-kpi-cards";
export { DashboardPageContent } from "./pages/dashboard-page-content";
export { SettingsPageContent } from "./pages/settings-page-content";
export { validatePortalP1, runPortalBoundaryAudit } from "./validation/validate-portal-p1";
export { validatePortalSession, assertPortalSessionResolverContract } from "./validation/validate-session";
export { SAAS_PRODUCT_PORTAL_P1_FREEZE } from "./freeze/v52-p1-meta";
export { SAAS_PRODUCT_PORTAL_P2_FREEZE } from "./freeze/v52-p2-meta";

export { SAAS_PRODUCT_PORTAL_META } from "./index-meta";
