import {
  WORKSPACE_QUOTE_INTEGRATION_P4_META,
  WORKSPACE_QUOTE_INTEGRATION_P4_TAG,
} from "./v56-p4-meta";

export const WORKSPACE_QUOTE_INTEGRATION_P4_FREEZE = {
  tag: WORKSPACE_QUOTE_INTEGRATION_P4_TAG,
  version: WORKSPACE_QUOTE_INTEGRATION_P4_META.version,
  status: WORKSPACE_QUOTE_INTEGRATION_P4_META.status,
  frozen: false,
  dependencyTag: WORKSPACE_QUOTE_INTEGRATION_P4_META.dependencyTag,
  upstreamDependencyTag: WORKSPACE_QUOTE_INTEGRATION_P4_META.upstreamDependencyTag,
  verifyChecks: WORKSPACE_QUOTE_INTEGRATION_P4_META.verifyChecks,
  nextHorizon: WORKSPACE_QUOTE_INTEGRATION_P4_META.nextHorizon,
  note: WORKSPACE_QUOTE_INTEGRATION_P4_META.note,
} as const;
