import {
  WORKSPACE_QUOTE_INTEGRATION_P2_META,
  WORKSPACE_QUOTE_INTEGRATION_P2_TAG,
} from "./v56-p2-meta";

export const WORKSPACE_QUOTE_INTEGRATION_P2_FREEZE = {
  tag: WORKSPACE_QUOTE_INTEGRATION_P2_TAG,
  version: WORKSPACE_QUOTE_INTEGRATION_P2_META.version,
  status: WORKSPACE_QUOTE_INTEGRATION_P2_META.status,
  frozen: false,
  dependencyTag: WORKSPACE_QUOTE_INTEGRATION_P2_META.dependencyTag,
  verifyChecks: WORKSPACE_QUOTE_INTEGRATION_P2_META.verifyChecks,
  nextHorizon: WORKSPACE_QUOTE_INTEGRATION_P2_META.nextHorizon,
  note: WORKSPACE_QUOTE_INTEGRATION_P2_META.note,
} as const;
