/**
 * ESCR — Retention public exports
 */

export {
  ESCR_1_ID,
  RETENTION_STATE_CAPABILITY,
  RETENTION_STATE_VERSION,
  ESCS_V1_BASELINE,
  RETENTION_STATES,
  retentionStateFromSignals,
  buildRetentionState,
  getRetentionState,
  retentionStateFingerprint,
  clearRetentionState,
  type RetentionStateLevel,
  type RetentionStateRecord,
  type RetentionState,
} from "./retention-state";

export {
  ESCR_2_ID,
  RETENTION_INTERVENTION_CAPABILITY,
  RETENTION_INTERVENTION_VERSION,
  ESCR1_RETENTION_STATE_BASELINE,
  RETENTION_INTERVENTIONS,
  retentionInterventionFromState,
  buildRetentionIntervention,
  getRetentionIntervention,
  retentionInterventionFingerprint,
  clearRetentionIntervention,
  ensureStateThenBuildRetentionIntervention,
  type RetentionInterventionKind,
  type RetentionInterventionRecord,
  type RetentionIntervention,
} from "./retention-intervention";

export {
  ESCR_3_ID,
  RETENTION_OUTCOME_CAPABILITY,
  RETENTION_OUTCOME_VERSION,
  ESCR2_RETENTION_INTERVENTION_BASELINE,
  RETENTION_OUTCOMES,
  retentionOutcomeFromIntervention,
  buildRetentionOutcome,
  getRetentionOutcome,
  retentionOutcomeFingerprint,
  clearRetentionOutcome,
  ensureInterventionThenBuildRetentionOutcome,
  type RetentionOutcomeKind,
  type RetentionOutcomeRecord,
  type RetentionOutcome,
} from "./retention-outcome";

export {
  ESCR_4_ID,
  RETENTION_REVIEW_CAPABILITY,
  RETENTION_REVIEW_VERSION,
  ESCR3_RETENTION_OUTCOME_BASELINE,
  RETENTION_REVIEW_STATUSES,
  retentionReviewStatusFromOutcome,
  buildRetentionReview,
  getRetentionReview,
  retentionReviewFingerprint,
  clearRetentionReview,
  ESCR_FREEZE_ID,
  ESCR_FREEZE_CAPABILITY,
  ESCR_FREEZE_VERSION,
  ESCR_FREEZE_CODENAME,
  ESCR_FREEZE_DATE,
  ENTERPRISE_SAAS_CUSTOMER_RETENTION_V1,
  ESCR_COMPONENTS,
  buildEscrFreeze,
  getEscrFreeze,
  escrFreezeFingerprint,
  clearEscrFreeze,
  ensureReviewThenBuildEscrFreeze,
  type RetentionReviewStatus,
  type RetentionReviewRecord,
  type RetentionReview,
  type EscrComponentStatus,
  type EscrComponentEntry,
  type EscrFreezeManifest,
  type EscrFreeze,
} from "./retention-freeze";
