/**
 * V60 P4 — White-label theme resolver
 */

import type { WhiteLabelTheme } from "../expansion.types";
import { getTenantBranding } from "./tenant.branding";

export const DEFAULT_THEME: WhiteLabelTheme = {
  primaryColor: "#ffffff",
  secondaryColor: "#18181b",
  companyName: "AI Fitness Solution",
  pdfHeader: "AI Fitness Solution",
  pdfFooter: "Confidential — Generated by AI Fitness Solution",
};

export function generateWhiteLabelTheme(input: {
  companyName: string;
  primaryColor?: string;
  secondaryColor?: string;
  logoUrl?: string;
  domain?: string;
}): WhiteLabelTheme {
  return {
    primaryColor: input.primaryColor ?? DEFAULT_THEME.primaryColor,
    secondaryColor: input.secondaryColor ?? DEFAULT_THEME.secondaryColor,
    logoUrl: input.logoUrl,
    companyName: input.companyName,
    domain: input.domain,
    pdfHeader: input.companyName,
    pdfFooter: `Confidential — ${input.companyName}`,
  };
}

export function resolveThemeForOrganization(organizationId: string): WhiteLabelTheme {
  const branding = getTenantBranding(organizationId);
  if (branding?.enabled && branding.theme) {
    return branding.theme;
  }
  return DEFAULT_THEME;
}

export function resolvePdfBranding(organizationId: string): { header: string; footer: string; logoUrl?: string } {
  const theme = resolveThemeForOrganization(organizationId);
  return {
    header: theme.pdfHeader ?? theme.companyName,
    footer: theme.pdfFooter ?? DEFAULT_THEME.pdfFooter!,
    logoUrl: theme.logoUrl,
  };
}
