import type { RuntimePolicyRule } from "../types";

/**
 * 企业治理默认策略（确定性，可审计）
 */
export const DEFAULT_ENTERPRISE_RUNTIME_POLICIES: RuntimePolicyRule[] = [
  {
    id: "POL_EXEC_SCORE_BLOCK",
    metric: "executiveScore",
    operator: "lt",
    value: 45,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_EXEC_SCORE_REVIEW",
    metric: "executiveScore",
    operator: "lt",
    value: 75,
    action: "require-executive-review",
    deterministic: true,
  },
  {
    id: "POL_EXEC_SCORE_CONDITIONAL",
    metric: "executiveScore",
    operator: "lt",
    value: 75,
    action: "conditional-release",
    deterministic: true,
  },
  {
    id: "POL_MANDATORY_MISSING",
    metric: "mandatoryMissing",
    operator: "gt",
    value: 0,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_COVERAGE_LOW",
    metric: "coverageRatio",
    operator: "lt",
    value: 0.5,
    action: "raise-governance-warning",
    deterministic: true,
  },
  {
    id: "POL_AUDIT_BLOCKED",
    metric: "auditBlocked",
    operator: "eq",
    value: true,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_AUDIT_BLOCKED_WARN",
    metric: "auditBlocked",
    operator: "eq",
    value: true,
    action: "raise-audit-warning",
    deterministic: true,
  },
  {
    id: "POL_AUDIT_REVIEW",
    metric: "auditReviewRequired",
    operator: "eq",
    value: true,
    action: "raise-audit-warning",
    deterministic: true,
  },
  {
    id: "POL_GOVERNANCE_HALT",
    metric: "governanceHalt",
    operator: "eq",
    value: true,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_GOVERNANCE_ESCALATE",
    metric: "governanceEscalate",
    operator: "eq",
    value: true,
    action: "raise-governance-warning",
    deterministic: true,
  },
  {
    id: "POL_OCR_TRACE",
    metric: "ocrTraceabilityComplete",
    operator: "eq",
    value: false,
    action: "conditional-release",
    deterministic: true,
  },
  {
    id: "POL_VALIDATION_REJECTED",
    metric: "validationRejected",
    operator: "eq",
    value: true,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_CRITICAL_COMPLIANCE",
    metric: "criticalComplianceCount",
    operator: "gt",
    value: 0,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_GATE_NOT_RELEASABLE",
    metric: "releasable",
    operator: "eq",
    value: false,
    action: "block-release",
    deterministic: true,
  },
  {
    id: "POL_CORRELATION_CRITICAL",
    metric: "correlationCriticalPathCount",
    operator: "gt",
    value: 0,
    action: "require-executive-review",
    deterministic: true,
  },
];
