import type { RequirementProfile } from "../shared/types";

export const REQUIREMENT_PROFILES: RequirementProfile[] = [
  {
    tenderId: "tender-sh-commercial-gym-2025-001",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 10,
    technicalRequirement: "Life Fitness LF-T5-001 commercial treadmill with console telemetry",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-sh-commercial-gym-2025-001",
    requirementType: "service",
    equipmentCategory: "Service",
    quantity: 1,
    technicalRequirement: "48h on-site service SLA in Shanghai with spare parts availability",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-bj-hotel-2025-002",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 8,
    technicalRequirement: "Technogym TG-SKILLRUN-001 premium treadmill for hotel fitness",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-bj-hotel-2025-002",
    requirementType: "installation",
    equipmentCategory: "Installation",
    quantity: 1,
    technicalRequirement: "After-hours installation with hotel noise compliance",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-cd-community-2025-003",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 6,
    technicalRequirement: "Shuhua SH-T8000-001 community-grade treadmill",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-cd-community-2025-003",
    requirementType: "maintenance",
    equipmentCategory: "Maintenance",
    quantity: 1,
    technicalRequirement: "3-year preventive maintenance plan with quarterly inspection",
    mandatory: false,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-gz-campus-2025-004",
    requirementType: "equipment",
    equipmentCategory: "Functional",
    quantity: 12,
    technicalRequirement: "Matrix MX-SDRIVE-001 functional training equipment",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-gz-campus-2025-004",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 6,
    technicalRequirement: "Matrix MX-TM-001 commercial treadmill for campus gym",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-sh-enterprise-2025-005",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 8,
    technicalRequirement: "Life Fitness LF-TM-001 enterprise treadmill package",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-sh-enterprise-2025-005",
    requirementType: "service",
    equipmentCategory: "Service",
    quantity: 1,
    technicalRequirement: "Enterprise SLA with dedicated engineer pool in East China",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-sz-fitness-club-2025-006",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 5,
    technicalRequirement: "Relax RX-TM-001 mid-market treadmill for fitness club",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-sz-fitness-club-2025-006",
    requirementType: "equipment",
    equipmentCategory: "Strength",
    quantity: 4,
    technicalRequirement: "BodyStrong BS-TM-001 strength equipment package",
    mandatory: false,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-nj-government-2025-007",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 6,
    technicalRequirement: "Precor PC-TM-001 government procurement compliant treadmill",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-nj-government-2025-007",
    requirementType: "installation",
    equipmentCategory: "Installation",
    quantity: 1,
    technicalRequirement: "Government facility safety certification and installation audit",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-wh-corporate-2025-008",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 7,
    technicalRequirement: "Impulse IM-TM-001 value treadmill for corporate gym",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-wh-corporate-2025-008",
    requirementType: "maintenance",
    equipmentCategory: "Maintenance",
    quantity: 1,
    technicalRequirement: "Annual maintenance contract with 72h response in Central China",
    mandatory: false,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-hz-medical-2025-009",
    requirementType: "equipment",
    equipmentCategory: "Elliptical",
    quantity: 4,
    technicalRequirement: "SportsArt SA-TM-001 low-impact elliptical for rehabilitation",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-hz-medical-2025-009",
    requirementType: "service",
    equipmentCategory: "Service",
    quantity: 1,
    technicalRequirement: "Medical facility compliant service protocol with documentation",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-cq-residential-2025-010",
    requirementType: "equipment",
    equipmentCategory: "Treadmill",
    quantity: 4,
    technicalRequirement: "DHZ DH-TM-001 residential club treadmill package",
    mandatory: true,
    mode: "tender-marketplace",
  },
  {
    tenderId: "tender-cq-residential-2025-010",
    requirementType: "installation",
    equipmentCategory: "Installation",
    quantity: 1,
    technicalRequirement: "Residential club delivery with elevator logistics planning",
    mandatory: true,
    mode: "tender-marketplace",
  },
];

export function getAllRequirementProfiles(): RequirementProfile[] {
  return [...REQUIREMENT_PROFILES];
}

export function getRequirementProfilesByTenderId(tenderId: string): RequirementProfile[] {
  return REQUIREMENT_PROFILES.filter((r) => r.tenderId === tenderId);
}
