import {
  V55_FOUNDATION_INTEGRITY_LOCKED,
  V55_QUOTE_FOUNDATION_DEPENDENCY_CHAIN,
  V55_QUOTE_FOUNDATION_LAYER_STACK,
  WORKSPACE_QUOTE_RUNTIME_P7_META,
  WORKSPACE_QUOTE_RUNTIME_P7_TAG,
} from "./v55-p7-meta";

export const WORKSPACE_QUOTE_RUNTIME_P7_FREEZE = {
  tag: WORKSPACE_QUOTE_RUNTIME_P7_TAG,
  version: WORKSPACE_QUOTE_RUNTIME_P7_META.version,
  status: WORKSPACE_QUOTE_RUNTIME_P7_META.status,
  frozen: false,
  dependencyTag: WORKSPACE_QUOTE_RUNTIME_P7_META.dependencyTag,
  verifyChecks: WORKSPACE_QUOTE_RUNTIME_P7_META.verifyChecks,
  layerStack: V55_QUOTE_FOUNDATION_LAYER_STACK,
  dependencyChain: V55_QUOTE_FOUNDATION_DEPENDENCY_CHAIN,
  integrityLock: V55_FOUNDATION_INTEGRITY_LOCKED,
  nextHorizon: WORKSPACE_QUOTE_RUNTIME_P7_META.nextHorizon,
  note: WORKSPACE_QUOTE_RUNTIME_P7_META.note,
} as const;
