import {
  GOVERNANCE_INCIDENT_RECOVERY_PROFILE_VERSION,
  type GovernanceIncidentRecoveryProfileRegistry,
} from "./incident-recovery-profile.types";

export function buildIncidentRecoveryProfileRegistry(): GovernanceIncidentRecoveryProfileRegistry {
  return {
    version: GOVERNANCE_INCIDENT_RECOVERY_PROFILE_VERSION,
    profiles: [
      {
        profileId: "profile-emergency-recovery",
        profileName: "emergency-recovery",
        category: "emergency",
        enabled: true,
        priority: 100,
        strategy: "rollback",
        allowAutomation: false,
        preferRollback: true,
        allowDegraded: true,
        requireManualIntervention: true,
        allowPartialRecovery: false,
        rules: [
          {
            ruleId: "rule-severe-failure",
            description: "Severe failure prefers emergency recovery.",
            severity: "critical",
            predicate: "severeFailure",
          },
        ],
        rationale: "Critical incidents prioritize rollback + human oversight.",
      },
      {
        profileId: "profile-audit-recovery",
        profileName: "audit-recovery",
        category: "audit",
        enabled: true,
        priority: 90,
        strategy: "replay",
        allowAutomation: true,
        preferRollback: false,
        allowDegraded: true,
        requireManualIntervention: false,
        allowPartialRecovery: true,
        rules: [
          {
            ruleId: "rule-audit-replay",
            description: "Replay available and audit required.",
            severity: "high",
            predicate: "auditRequired",
          },
        ],
        rationale: "Audit-sensitive incidents use replay first.",
      },
      {
        profileId: "profile-degraded-recovery",
        profileName: "degraded-recovery",
        category: "degraded",
        enabled: true,
        priority: 85,
        strategy: "degraded",
        allowAutomation: true,
        preferRollback: false,
        allowDegraded: true,
        requireManualIntervention: false,
        allowPartialRecovery: true,
        rules: [
          {
            ruleId: "rule-store-unavailable",
            description: "Store unavailable enters degraded recovery.",
            severity: "high",
            predicate: "storeUnavailable",
          },
        ],
        rationale: "Unreliable store requires controlled degraded mode.",
      },
      {
        profileId: "profile-manual-recovery",
        profileName: "manual-recovery",
        category: "manual",
        enabled: true,
        priority: 80,
        strategy: "manualIntervention",
        allowAutomation: false,
        preferRollback: false,
        allowDegraded: true,
        requireManualIntervention: true,
        allowPartialRecovery: false,
        rules: [
          {
            ruleId: "rule-manual-required",
            description: "Manual intervention required.",
            severity: "high",
            predicate: "manualRequired",
          },
        ],
        rationale: "Approval-gated incidents require operators.",
      },
      {
        profileId: "profile-partial-recovery",
        profileName: "partial-recovery",
        category: "partial",
        enabled: true,
        priority: 70,
        strategy: "partial",
        allowAutomation: true,
        preferRollback: false,
        allowDegraded: false,
        requireManualIntervention: false,
        allowPartialRecovery: true,
        rules: [
          {
            ruleId: "rule-partial-only",
            description: "Only subset modules recoverable.",
            severity: "medium",
            predicate: "partialOnly",
          },
        ],
        rationale: "Fallback to minimal viable context recovery.",
      },
      {
        profileId: "profile-standard-recovery",
        profileName: "standard-recovery",
        category: "standard",
        enabled: true,
        priority: 10,
        strategy: "retry",
        allowAutomation: true,
        preferRollback: false,
        allowDegraded: false,
        requireManualIntervention: false,
        allowPartialRecovery: true,
        rules: [
          {
            ruleId: "rule-checkpoint-available",
            description: "Checkpoint available under normal scenario.",
            severity: "low",
            predicate: "checkpointAvailable",
          },
        ],
        rationale: "Default profile for healthy recoverable incidents.",
      },
    ],
  };
}
