import { GOVERNANCE_RULEBOOK_VERSION, type GovernanceRulebook } from "./rulebook.types";

export function buildDefaultGovernanceRulebook(): GovernanceRulebook {
  return {
    rulebookId: "governance-rulebook-default",
    version: GOVERNANCE_RULEBOOK_VERSION,
    entries: [
      {
        ruleId: "rule-high-risk-approval",
        ruleName: "High risk recommendation requires approval",
        category: "approval",
        enabled: true,
        priority: 100,
        severity: "high",
        description: "High risk recommendation must pass manual approval.",
        rationale: "Prevent high-risk automatic progression.",
        triggerReason: "recommendation priority high or critical",
        triggers: [
          { field: "kind", scope: "recommendation", threshold: { type: "enum", allowed: ["recommendation"] } },
          { field: "priority", scope: "recommendation", threshold: { type: "level", allowed: ["high", "critical"] } },
        ],
        actions: [{ to: "approvals", label: "manual-approval-required" }],
      },
      {
        ruleId: "rule-severe-anomaly-escalation",
        ruleName: "Severe anomaly escalates",
        category: "escalation",
        enabled: true,
        priority: 95,
        severity: "critical",
        description: "Critical anomaly requires escalation.",
        rationale: "Protect production reliability.",
        triggerReason: "critical anomaly detected",
        triggers: [
          { field: "kind", scope: "anomaly", threshold: { type: "enum", allowed: ["anomaly"] } },
          { field: "priority", scope: "anomaly", threshold: { type: "level", allowed: ["critical"] } },
        ],
        actions: [{ to: "escalation", label: "escalate-anomaly" }],
      },
      {
        ruleId: "rule-bottleneck-control",
        ruleName: "Bottleneck requires control",
        category: "control",
        enabled: true,
        priority: 90,
        severity: "high",
        description: "Bottleneck candidate must generate controls.",
        rationale: "Ensure bottleneck convergence.",
        triggerReason: "bottleneck exists",
        triggers: [
          { field: "kind", scope: "bottleneck", threshold: { type: "enum", allowed: ["bottleneck"] } },
        ],
        actions: [{ to: "controls", label: "add-bottleneck-control" }],
      },
      {
        ruleId: "rule-low-confidence-review",
        ruleName: "Low confidence decision needs review",
        category: "approval",
        enabled: true,
        priority: 85,
        severity: "high",
        description: "Decision confidence below threshold requires manual review.",
        rationale: "Avoid low-confidence automation.",
        triggerReason: "decision confidence low",
        triggers: [
          { field: "kind", scope: "decision", threshold: { type: "enum", allowed: ["decision"] } },
          { field: "confidence", scope: "decision", threshold: { type: "number", operator: "lt", value: 80 } },
        ],
        actions: [
          { to: "approvals", label: "manual-review" },
          { to: "auditTrail", label: "record-low-confidence-review" },
        ],
      },
      {
        ruleId: "rule-summary-open-loop-exception",
        ruleName: "Open-loop summary marks exception",
        category: "exception",
        enabled: true,
        priority: 80,
        severity: "medium",
        description: "Summary with unresolved keywords should open exception.",
        rationale: "Track unresolved operation loops.",
        triggerReason: "summary unresolved markers",
        triggers: [
          { field: "kind", scope: "summary", threshold: { type: "enum", allowed: ["summary"] } },
          {
            field: "title",
            scope: "summary",
            threshold: {
              type: "keywords",
              words: ["investigate", "escalate", "hold", "degraded", "critical", "watch"],
            },
          },
        ],
        actions: [
          { to: "exceptions", label: "mark-open-loop-exception" },
          { to: "auditTrail", label: "record-open-loop" },
        ],
      },
      {
        ruleId: "rule-large-impact-escalation",
        ruleName: "Large impact recommendation escalates",
        category: "escalation",
        enabled: true,
        priority: 78,
        severity: "high",
        description: "Large-impact recommendation must escalate.",
        rationale: "Require higher oversight for broad impact.",
        triggerReason: "recommendation evidence breadth",
        triggers: [
          { field: "kind", scope: "recommendation", threshold: { type: "enum", allowed: ["recommendation"] } },
          { field: "evidenceCount", scope: "recommendation", threshold: { type: "number", operator: "gte", value: 3 } },
        ],
        actions: [{ to: "escalation", label: "escalate-large-impact" }],
      },
      {
        ruleId: "rule-priority-conflict-arbitration",
        ruleName: "Rule conflicts resolve by priority",
        category: "audit",
        enabled: true,
        priority: 75,
        severity: "medium",
        description: "When multiple rules target the same action, higher priority wins.",
        rationale: "Deterministic governance under overlapping matches.",
        triggerReason: "governance evaluation active",
        triggers: [
          { field: "kind", scope: "summary", threshold: { type: "enum", allowed: ["summary"] } },
        ],
        actions: [{ to: "auditTrail", label: "record-priority-arbitration" }],
      },
      {
        ruleId: "rule-summary-rule-conclusion",
        ruleName: "Summary must include rule conclusion",
        category: "summary",
        enabled: true,
        priority: 60,
        severity: "low",
        description: "Governance summary includes rulebook conclusion.",
        rationale: "Improve explainability and audit readability.",
        triggerReason: "summary always enforced",
        triggers: [
          { field: "kind", scope: "summary", threshold: { type: "enum", allowed: ["summary"] } },
        ],
        actions: [{ to: "governanceSummary", label: "append-rulebook-conclusion" }],
      },
    ],
  };
}
