import type { GovernanceSummary, OperationalGovernanceRuntimeResult } from "./types";

export function buildGovernanceSummary(
  runtime: Omit<OperationalGovernanceRuntimeResult, "summary">,
): GovernanceSummary {
  return {
    summaryId: `gsum-${runtime.inputSnapshot.deploymentId.slice(0, 8)}`,
    text: [
      `governed=${runtime.isGoverned}`,
      `approvals=${runtime.approvalCount}`,
      `escalation=${runtime.escalationCount}`,
      `exceptions=${runtime.exceptions.length}`,
      `rules.matched=${runtime.matchedRules.length}`,
      `rules.unmatched=${runtime.unmatchedRules.length}`,
      `rule.conclusion=${runtime.matchedRules.length > 0 ? "active" : "baseline"}`,
      `governanceScore=${runtime.governanceScore}`,
      `governanceConfidence=${runtime.governanceConfidence}`,
      `rulebookVersion=${runtime.rulebookVersion}`,
      `rulebookSummary=${runtime.rulebookSummary}`,
      `policyPackMode=${runtime.policyPackMode}`,
      `policyPackSummary=${runtime.policyPackSummary}`,
      `orchestrationState=${runtime.orchestrationState.status}`,
      `orchestrationSummary=${runtime.orchestrationSummary}`,
      `lifecycleStatus=${runtime.lifecycleStatus}`,
      `lifecycleSummary=${runtime.lifecycleSummary}`,
      `persistenceStatus=${runtime.persistenceStatus}`,
      `persistenceSummary=${runtime.persistenceSummary}`,
      `storeBackend=${runtime.storeBackend}`,
      `storeSummary=${runtime.storeSummary}`,
      `recoveryStatus=${runtime.recoveryStatus}`,
      `recoverySummary=${runtime.recoverySummary}`,
      `incidentProfile=${runtime.incidentRecoveryProfileSnapshot.profileName}`,
      `incidentProfileSummary=${runtime.incidentRecoveryProfileSummary}`,
      `incidentProfileConfig=${runtime.incidentRecoveryProfileConfigSummary}`,
      `incidentProfileJson=${runtime.incidentRecoveryProfileJsonSourceSummary}`,
      `incidentProfileJsonGuard=${runtime.incidentRecoveryProfileJsonSchemaGuardSummary}`,
      `incidentProfileJsonEvolution=${runtime.incidentRecoveryProfileJsonSchemaEvolutionSummary}`,
      `incidentProfileMigrationRegistry=${runtime.incidentRecoveryProfileMigrationRuleRegistrySummary}`,
      `incidentProfileRenderingPolicy=${runtime.incidentRecoveryProfileRenderingPolicySummary}`,
      `incidentProfileMigrationExecution=${runtime.incidentRecoveryProfileMigrationExecutionSummary}`,
      `incidentProfileCanonicalContract=${runtime.incidentRecoveryProfileCanonicalContractSummary}`,
      `incidentProfileExternalConsumerRegistry=${runtime.incidentRecoveryProfileExternalConsumerRegistrySummary}`,
      `incidentProfileExternalConsumerRegistrySourceAdapter=${runtime.incidentRecoveryProfileExternalConsumerRegistrySourceAdapterSummary}`,
      `incidentProfileExternalConsumerRegistryConfig=${runtime.incidentRecoveryProfileExternalConsumerRegistryConfigSummary}`,
      `intelligence=${runtime.inputSnapshot.intelligenceRuntimeId}`,
    ].join(" "),
    source: "governance.summary",
    traceId: `trace-summary-${runtime.inputSnapshot.deploymentId}`,
  };
}
