export const QUOTE_EVENT_TYPE_LIFECYCLE_CHANGED = "LIFECYCLE_CHANGED" as const;
export const QUOTE_EVENT_TYPE_JOB_REGISTERED = "JOB_REGISTERED" as const;
export const QUOTE_EVENT_TYPE_JOB_DISPATCHED = "JOB_DISPATCHED" as const;
export const QUOTE_EVENT_TYPE_JOB_STARTED = "JOB_STARTED" as const;
export const QUOTE_EVENT_TYPE_JOB_COMPLETED = "JOB_COMPLETED" as const;
export const QUOTE_EVENT_TYPE_JOB_FAILED = "JOB_FAILED" as const;
export const QUOTE_EVENT_TYPE_EXECUTION_ACCEPTED = "EXECUTION_ACCEPTED" as const;
export const QUOTE_EVENT_TYPE_EXECUTION_RUNNING = "EXECUTION_RUNNING" as const;
export const QUOTE_EVENT_TYPE_EXECUTION_DONE = "EXECUTION_DONE" as const;
export const QUOTE_EVENT_TYPE_EXECUTION_ERROR = "EXECUTION_ERROR" as const;
export const QUOTE_EVENT_TYPE_STATUS_SYNCED = "STATUS_SYNCED" as const;
export const QUOTE_EVENT_TYPE_HISTORY_RECORDED = "HISTORY_RECORDED" as const;

export const QUOTE_EVENT_TYPES = [
  QUOTE_EVENT_TYPE_LIFECYCLE_CHANGED,
  QUOTE_EVENT_TYPE_JOB_REGISTERED,
  QUOTE_EVENT_TYPE_JOB_DISPATCHED,
  QUOTE_EVENT_TYPE_JOB_STARTED,
  QUOTE_EVENT_TYPE_JOB_COMPLETED,
  QUOTE_EVENT_TYPE_JOB_FAILED,
  QUOTE_EVENT_TYPE_EXECUTION_ACCEPTED,
  QUOTE_EVENT_TYPE_EXECUTION_RUNNING,
  QUOTE_EVENT_TYPE_EXECUTION_DONE,
  QUOTE_EVENT_TYPE_EXECUTION_ERROR,
  QUOTE_EVENT_TYPE_STATUS_SYNCED,
  QUOTE_EVENT_TYPE_HISTORY_RECORDED,
] as const;

export type QuoteEventType = (typeof QUOTE_EVENT_TYPES)[number];

export const QUOTE_EVENT_CONTRACT_VERSION = "v58-quote-event-contract-v1" as const;
