/**
 * V100 — Pilot capability catalog (static registry of V80–V99, read-only)
 */

import type { CapabilityEntry } from "./signoff.types";

const RAW_CATALOG: Array<Omit<CapabilityEntry, "readOnly">> = [
  {
    version: "V80",
    versionConstant: "V80_PILOT_SIGNOFF_VERSION",
    capability: "Tender Intake & Sign-off",
    modulePath: "lib/pilot/v80",
    route: "/pilot/intake",
    apiRoute: "/api/pilot/v80",
    verifyScript: "verify:v80-pilot-signoff",
  },
  {
    version: "V81",
    versionConstant: "V81_DELIVERY_OPS_VERSION",
    capability: "Delivery Ops & Tracking",
    modulePath: "lib/pilot/v81",
    route: "/pilot/delivery-ops",
    apiRoute: "/api/pilot/v81",
    verifyScript: "verify:v81-delivery-ops",
  },
  {
    version: "V82",
    versionConstant: "V82_DELIVERY_ANALYTICS_VERSION",
    capability: "Delivery Analytics",
    modulePath: "lib/pilot/v82",
    route: "/pilot/delivery-analytics",
    apiRoute: "/api/pilot/v82",
    verifyScript: "verify:v82-delivery-analytics",
  },
  {
    version: "V83",
    versionConstant: "V83_DELIVERY_INTELLIGENCE_VERSION",
    capability: "Delivery Intelligence",
    modulePath: "lib/pilot/v83",
    route: "/pilot/delivery-intelligence",
    apiRoute: "/api/pilot/v83",
    verifyScript: "verify:v83-delivery-intelligence",
  },
  {
    version: "V84",
    versionConstant: "V84_CUSTOMER_SUCCESS_VERSION",
    capability: "Customer Success Follow-up",
    modulePath: "lib/pilot/v84",
    route: "/pilot/customer-success",
    apiRoute: "/api/pilot/v84",
    verifyScript: "verify:v84-customer-success",
  },
  {
    version: "V85",
    versionConstant: "V85_ACCOUNT_HEALTH_VERSION",
    capability: "Account Health & Renewal",
    modulePath: "lib/pilot/v85",
    route: "/pilot/account-health",
    apiRoute: "/api/pilot/v85",
    verifyScript: "verify:v85-account-health",
  },
  {
    version: "V86",
    versionConstant: "V86_RENEWAL_OPS_VERSION",
    capability: "Renewal Ops & Churn Prevention",
    modulePath: "lib/pilot/v86",
    route: "/pilot/renewal-ops",
    apiRoute: "/api/pilot/v86",
    verifyScript: "verify:v86-renewal-ops",
  },
  {
    version: "V87",
    versionConstant: "V87_REVENUE_OPS_VERSION",
    capability: "Revenue Ops & Forecast Control",
    modulePath: "lib/pilot/v87",
    route: "/pilot/revenue-ops",
    apiRoute: "/api/pilot/v87",
    verifyScript: "verify:v87-revenue-ops",
  },
  {
    version: "V88",
    versionConstant: "V88_GROWTH_PLANNING_VERSION",
    capability: "Growth Planning & Forecast",
    modulePath: "lib/pilot/v88",
    route: "/pilot/growth-planning",
    apiRoute: "/api/pilot/v88",
    verifyScript: "verify:v88-growth-planning",
  },
  {
    version: "V89",
    versionConstant: "V89_EXPANSION_OPS_VERSION",
    capability: "Expansion Ops & Account Growth",
    modulePath: "lib/pilot/v89",
    route: "/pilot/expansion-ops",
    apiRoute: "/api/pilot/v89",
    verifyScript: "verify:v89-expansion-ops",
  },
  {
    version: "V90",
    versionConstant: "V90_PORTFOLIO_VERSION",
    capability: "Portfolio Intelligence & Segmentation",
    modulePath: "lib/pilot/v90",
    route: "/pilot/portfolio-intelligence",
    apiRoute: "/api/pilot/v90",
    verifyScript: "verify:v90-portfolio",
  },
  {
    version: "V91",
    versionConstant: "V91_PORTFOLIO_OPS_VERSION",
    capability: "Portfolio Ops & Strategic Actions",
    modulePath: "lib/pilot/v91",
    route: "/pilot/portfolio-ops",
    apiRoute: "/api/pilot/v91",
    verifyScript: "verify:v91-portfolio-ops",
  },
  {
    version: "V92",
    versionConstant: "V92_BOARD_GOVERNANCE_VERSION",
    capability: "Executive Portfolio Governance & Board Review",
    modulePath: "lib/pilot/v92",
    route: "/pilot/board-governance",
    apiRoute: "/api/pilot/v92",
    verifyScript: "verify:v92-board-governance",
  },
  {
    version: "V93",
    versionConstant: "V93_EXECUTIVE_REPORTING_VERSION",
    capability: "Executive Reporting & Board Packet",
    modulePath: "lib/pilot/v93",
    route: "/pilot/executive-reporting",
    apiRoute: "/api/pilot/v93/executive-reporting",
    verifyScript: "verify:v93-executive-reporting",
  },
  {
    version: "V94",
    versionConstant: "V94_EXECUTIVE_BRIEFING_VERSION",
    capability: "Executive Briefing & Decision Support",
    modulePath: "lib/pilot/v94",
    route: "/pilot/executive-briefing",
    apiRoute: "/api/pilot/v94/executive-briefing",
    verifyScript: "verify:v94-executive-briefing",
  },
  {
    version: "V95",
    versionConstant: "V95_EXECUTIVE_ACTIONS_VERSION",
    capability: "Executive Actions & Governance Closure",
    modulePath: "lib/pilot/v95",
    route: "/pilot/executive-actions",
    apiRoute: "/api/pilot/v95/executive-actions",
    verifyScript: "verify:v95-executive-actions",
  },
  {
    version: "V96",
    versionConstant: "V96_EXECUTIVE_ARCHIVE_VERSION",
    capability: "Executive Archive & Audit Retrieval",
    modulePath: "lib/pilot/v96",
    route: "/pilot/executive-archive",
    apiRoute: "/api/pilot/v96/executive-archive",
    verifyScript: "verify:v96-executive-archive",
  },
  {
    version: "V97",
    versionConstant: "V97_EXECUTIVE_COMPLIANCE_VERSION",
    capability: "Executive Compliance Review & Retention Policy",
    modulePath: "lib/pilot/v97",
    route: "/pilot/executive-compliance",
    apiRoute: "/api/pilot/v97/executive-compliance",
    verifyScript: "verify:v97-executive-compliance",
  },
  {
    version: "V98",
    versionConstant: "V98_POLICY_ENFORCEMENT_VERSION",
    capability: "Compliance Automation & Policy Enforcement",
    modulePath: "lib/pilot/v98",
    route: "/pilot/policy-enforcement",
    apiRoute: "/api/pilot/v98/policy-enforcement",
    verifyScript: "verify:v98-policy-enforcement",
  },
  {
    version: "V99",
    versionConstant: "V99_PRODUCTION_READINESS_VERSION",
    capability: "Platform Readiness & Production Certification",
    modulePath: "lib/pilot/v99",
    route: "/pilot/production-readiness",
    apiRoute: "/api/pilot/v99/production-readiness",
    verifyScript: "verify:v99-production-readiness",
  },
];

export function getCapabilityCatalog(): CapabilityEntry[] {
  return RAW_CATALOG.map((entry) => ({ ...entry, readOnly: true as const }));
}

export function getCapabilityByVersion(version: string): CapabilityEntry | null {
  return getCapabilityCatalog().find((c) => c.version === version) ?? null;
}
