/**
 * Enterprise Platform (EP) — public barrel
 * Baseline: v80-pilot-ga-1.0.0
 */

export {
  EP_1_ID,
  EP_WP1_ID,
  EP_ORGANIZATION_REGISTRY_BASELINE,
  EP_ORGANIZATION_REGISTRY_VERSION,
  ORGANIZATION_REGISTRY_CAPABILITY,
  ORGANIZATION_TIERS,
  ORGANIZATION_TYPES,
  ORGANIZATION_STATUSES,
  buildOrganizationRegistry,
  getOrganizationRegistry,
  organizationRegistryFingerprint,
  clearOrganizationRegistry,
  type OrganizationRegistry,
  type OrganizationTier,
  type OrganizationType,
  type OrganizationStatus,
} from "./organization-registry";

export {
  EP_WP2_ID,
  EP_DEPARTMENT_REGISTRY_BASELINE,
  EP_DEPARTMENT_REGISTRY_VERSION,
  DEPARTMENT_REGISTRY_CAPABILITY,
  DEPARTMENT_TYPES,
  DEPARTMENT_STATUSES,
  buildDepartmentRegistry,
  getDepartmentRegistry,
  departmentRegistryFingerprint,
  clearDepartmentRegistry,
  type DepartmentRegistry,
  type DepartmentType,
  type DepartmentStatus,
} from "./department-registry";

export {
  EP_WP3_ID,
  EP_TEAM_REGISTRY_BASELINE,
  EP_TEAM_REGISTRY_VERSION,
  TEAM_REGISTRY_CAPABILITY,
  TEAM_TYPES,
  TEAM_STATUSES,
  buildTeamRegistry,
  getTeamRegistry,
  teamRegistryFingerprint,
  clearTeamRegistry,
  type TeamRegistry,
  type TeamType,
  type TeamStatus,
} from "./team-registry";

export {
  EP_WP4_ID,
  EP_USER_REGISTRY_BASELINE,
  EP_USER_REGISTRY_VERSION,
  USER_REGISTRY_CAPABILITY,
  USER_ROLES,
  USER_STATUSES,
  buildUserRegistry,
  getUserRegistry,
  userRegistryFingerprint,
  clearUserRegistry,
  type UserRegistry,
  type UserRole,
  type UserStatus,
} from "./user-registry";

export {
  EP_WP5_ID,
  EP_ROLE_REGISTRY_BASELINE,
  EP_ROLE_REGISTRY_VERSION,
  ROLE_REGISTRY_CAPABILITY,
  ROLE_TYPES,
  ROLE_STATUSES,
  buildRoleRegistry,
  getRoleRegistry,
  roleRegistryFingerprint,
  clearRoleRegistry,
  type RoleRegistry,
  type RoleType,
  type RoleStatus,
} from "./role-registry";

export {
  EP_WP6_ID,
  EP_PERMISSION_REGISTRY_BASELINE,
  EP_PERMISSION_REGISTRY_VERSION,
  PERMISSION_REGISTRY_CAPABILITY,
  PERMISSION_RESOURCES,
  PERMISSION_ACTIONS,
  PERMISSION_STATUSES,
  buildPermissionRegistry,
  getPermissionRegistry,
  permissionRegistryFingerprint,
  clearPermissionRegistry,
  type PermissionRegistry,
  type PermissionResource,
  type PermissionAction,
  type PermissionStatus,
} from "./permission-registry";

export {
  EP_WP7_ID,
  EP_MEMBERSHIP_REGISTRY_BASELINE,
  EP_MEMBERSHIP_REGISTRY_VERSION,
  MEMBERSHIP_REGISTRY_CAPABILITY,
  MEMBERSHIP_STATUSES,
  buildMembershipRegistry,
  getMembershipRegistry,
  membershipRegistryFingerprint,
  clearMembershipRegistry,
  type MembershipRegistry,
  type MembershipStatus,
} from "./membership-registry";

export {
  EP_WP8_ID,
  EP_ACCESS_REGISTRY_BASELINE,
  EP_ACCESS_REGISTRY_VERSION,
  ACCESS_REGISTRY_CAPABILITY,
  ACCESS_STATUSES,
  buildAccessRegistry,
  getAccessRegistry,
  accessRegistryFingerprint,
  clearAccessRegistry,
  type AccessRegistry,
  type AccessStatus,
} from "./access-registry";

export {
  EP_WP9_ID,
  EP_POLICY_REGISTRY_BASELINE,
  EP_POLICY_REGISTRY_VERSION,
  POLICY_REGISTRY_CAPABILITY,
  POLICY_EFFECTS,
  POLICY_STATUSES,
  buildPolicyRegistry,
  getPolicyRegistry,
  policyRegistryFingerprint,
  clearPolicyRegistry,
  type PolicyRegistry,
  type PolicyEffect,
  type PolicyStatus,
} from "./policy-registry";

export {
  EP_WP10_ID,
  EP_ASSIGNMENT_REGISTRY_BASELINE,
  EP_ASSIGNMENT_REGISTRY_VERSION,
  ASSIGNMENT_REGISTRY_CAPABILITY,
  ASSIGNMENT_STATUSES,
  buildAssignmentRegistry,
  getAssignmentRegistry,
  assignmentRegistryFingerprint,
  clearAssignmentRegistry,
  type AssignmentRegistry,
  type AssignmentStatus,
} from "./assignment-registry";

export {
  EP_WP11_ID,
  EP_NOTIFICATION_REGISTRY_BASELINE,
  EP_NOTIFICATION_REGISTRY_VERSION,
  NOTIFICATION_REGISTRY_CAPABILITY,
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUSES,
  buildNotificationRegistry,
  getNotificationRegistry,
  notificationRegistryFingerprint,
  clearNotificationRegistry,
  type NotificationRegistry,
  type NotificationType,
  type NotificationChannel,
  type NotificationStatus,
} from "./notification-registry";

export {
  EP_WP12_ID,
  EP_ALERT_REGISTRY_BASELINE,
  EP_ALERT_REGISTRY_VERSION,
  ALERT_REGISTRY_CAPABILITY,
  ALERT_TYPES,
  ALERT_SEVERITIES,
  ALERT_STATUSES,
  buildAlertRegistry,
  getAlertRegistry,
  alertRegistryFingerprint,
  clearAlertRegistry,
  type AlertRegistry,
  type AlertType,
  type AlertSeverity,
  type AlertStatus,
} from "./alert-registry";

export {
  EP_WP13_ID,
  EP_ESCALATION_REGISTRY_BASELINE,
  EP_ESCALATION_REGISTRY_VERSION,
  ESCALATION_REGISTRY_CAPABILITY,
  ESCALATION_TYPES,
  ESCALATION_PRIORITIES,
  ESCALATION_STATUSES,
  buildEscalationRegistry,
  getEscalationRegistry,
  escalationRegistryFingerprint,
  clearEscalationRegistry,
  type EscalationRegistry,
  type EscalationType,
  type EscalationPriority,
  type EscalationStatus,
} from "./escalation-registry";

export {
  EP_WP14_ID,
  EP_WORKFLOW_REGISTRY_BASELINE,
  EP_WORKFLOW_REGISTRY_VERSION,
  WORKFLOW_REGISTRY_CAPABILITY,
  WORKFLOW_TYPES,
  WORKFLOW_STATUSES,
  buildWorkflowRegistry,
  getWorkflowRegistry,
  workflowRegistryFingerprint,
  clearWorkflowRegistry,
  type WorkflowRegistry,
  type WorkflowType,
  type WorkflowStatus,
} from "./workflow-registry";

export {
  EP_WP15_ID,
  EP_APPROVAL_REGISTRY_BASELINE,
  EP_APPROVAL_REGISTRY_VERSION,
  APPROVAL_REGISTRY_CAPABILITY,
  APPROVAL_TYPES,
  APPROVAL_STATUSES,
  buildApprovalRegistry,
  getApprovalRegistry,
  approvalRegistryFingerprint,
  clearApprovalRegistry,
  type ApprovalRegistry,
  type ApprovalType,
  type ApprovalStatus,
} from "./approval-registry";

export {
  EP_WP16_ID,
  EP_REVIEW_REGISTRY_BASELINE,
  EP_REVIEW_REGISTRY_VERSION,
  REVIEW_REGISTRY_CAPABILITY,
  REVIEW_TYPES,
  REVIEW_STATUSES,
  buildReviewRegistry,
  getReviewRegistry,
  reviewRegistryFingerprint,
  clearReviewRegistry,
  type ReviewRegistry,
  type ReviewType,
  type ReviewStatus,
} from "./review-registry";

export {
  EP_WP17_ID,
  EP_AUDIT_REGISTRY_BASELINE,
  EP_AUDIT_REGISTRY_VERSION,
  AUDIT_REGISTRY_CAPABILITY,
  AUDIT_TYPES,
  AUDIT_STATUSES,
  buildAuditRegistry,
  getAuditRegistry,
  auditRegistryFingerprint,
  clearAuditRegistry,
  type AuditRegistry,
  type AuditType,
  type AuditStatus,
} from "./audit-registry";

export {
  EP_WP18_ID,
  EP_COMPLIANCE_REGISTRY_BASELINE,
  EP_COMPLIANCE_REGISTRY_VERSION,
  COMPLIANCE_REGISTRY_CAPABILITY,
  COMPLIANCE_TYPES,
  COMPLIANCE_STATUSES,
  buildComplianceRegistry,
  getComplianceRegistry,
  complianceRegistryFingerprint,
  clearComplianceRegistry,
  type ComplianceRegistry,
  type ComplianceType,
  type ComplianceStatus,
} from "./compliance-registry";

export {
  EP_WP19_ID,
  EP_CONTROL_REGISTRY_BASELINE,
  EP_CONTROL_REGISTRY_VERSION,
  CONTROL_REGISTRY_CAPABILITY,
  CONTROL_TYPES,
  CONTROL_STATUSES,
  buildControlRegistry,
  getControlRegistry,
  controlRegistryFingerprint,
  clearControlRegistry,
  type ControlRegistry,
  type ControlType,
  type ControlStatus,
} from "./control-registry";

export {
  EP_WP20_ID,
  EP_RISK_REGISTRY_BASELINE,
  EP_RISK_REGISTRY_VERSION,
  RISK_REGISTRY_CAPABILITY,
  RISK_TYPES,
  RISK_STATUSES,
  buildRiskRegistry,
  getRiskRegistry,
  riskRegistryFingerprint,
  clearRiskRegistry,
  type RiskRegistry,
  type RiskType,
  type RiskStatus,
} from "./risk-registry";

export {
  EP_WP21_ID,
  EP_ISSUE_REGISTRY_BASELINE,
  EP_ISSUE_REGISTRY_VERSION,
  ISSUE_REGISTRY_CAPABILITY,
  ISSUE_TYPES,
  ISSUE_STATUSES,
  buildIssueRegistry,
  getIssueRegistry,
  issueRegistryFingerprint,
  clearIssueRegistry,
  type IssueRegistry,
  type IssueType,
  type IssueStatus,
} from "./issue-registry";

export {
  EP_WP22_ID,
  EP_RESOLUTION_REGISTRY_BASELINE,
  EP_RESOLUTION_REGISTRY_VERSION,
  RESOLUTION_REGISTRY_CAPABILITY,
  RESOLUTION_TYPES,
  RESOLUTION_STATUSES,
  buildResolutionRegistry,
  getResolutionRegistry,
  resolutionRegistryFingerprint,
  clearResolutionRegistry,
  type ResolutionRegistry,
  type ResolutionType,
  type ResolutionStatus,
} from "./resolution-registry";

export {
  EP_WP23_ID,
  EP_REMEDY_REGISTRY_BASELINE,
  EP_REMEDY_REGISTRY_VERSION,
  REMEDY_REGISTRY_CAPABILITY,
  REMEDY_TYPES,
  REMEDY_STATUSES,
  buildRemedyRegistry,
  getRemedyRegistry,
  remedyRegistryFingerprint,
  clearRemedyRegistry,
  type RemedyRegistry,
  type RemedyType,
  type RemedyStatus,
} from "./remedy-registry";

export {
  EP_WP24_ID,
  EP_RECOVERY_REGISTRY_BASELINE,
  EP_RECOVERY_REGISTRY_VERSION,
  RECOVERY_REGISTRY_CAPABILITY,
  RECOVERY_TYPES,
  RECOVERY_STATUSES,
  buildRecoveryRegistry,
  getRecoveryRegistry,
  recoveryRegistryFingerprint,
  clearRecoveryRegistry,
  type RecoveryRegistry,
  type RecoveryType,
  type RecoveryStatus,
} from "./recovery-registry";

export {
  EP_WP25_ID,
  EP_RESTORE_REGISTRY_BASELINE,
  EP_RESTORE_REGISTRY_VERSION,
  RESTORE_REGISTRY_CAPABILITY,
  RESTORE_TYPES,
  RESTORE_STATUSES,
  buildRestoreRegistry,
  getRestoreRegistry,
  restoreRegistryFingerprint,
  clearRestoreRegistry,
  type RestoreRegistry,
  type RestoreType,
  type RestoreStatus,
} from "./restore-registry";

export {
  EP_WP26_ID,
  EP_1_FREEZE_VERSION,
  EP_1_CODENAME,
  EP_1_FREEZE_DATE,
  EP_1_BASELINE,
  EP_1_WORK_PACKAGES,
  EP_1_DEPENDENCY_CHAIN,
  EP_1_CORE_MODELS_UNCHANGED,
  buildEp1Manifest,
  computeEp1Fingerprint,
  listEp1ArtifactPresence,
  validateEp1DependencyChain,
  type Ep1Manifest,
  type Ep1WorkPackageEntry,
  type Ep1WorkPackageStatus,
} from "./ep1-manifest";

export {
  EP_2_ID,
  EP_2_WP1_ID,
  EP_WORKSPACE_REGISTRY_BASELINE,
  EP_WORKSPACE_REGISTRY_VERSION,
  WORKSPACE_REGISTRY_CAPABILITY,
  WORKSPACE_TYPES,
  WORKSPACE_STATUSES,
  buildWorkspaceRegistry,
  getWorkspaceRegistry,
  workspaceRegistryFingerprint,
  clearWorkspaceRegistry,
  type WorkspaceRegistry,
  type WorkspaceType,
  type WorkspaceStatus,
} from "./workspace-registry";

export {
  EP_2_WP2_ID,
  EP_WORKSPACE_MEMBER_REGISTRY_BASELINE,
  EP_WORKSPACE_MEMBER_REGISTRY_VERSION,
  WORKSPACE_MEMBER_REGISTRY_CAPABILITY,
  WORKSPACE_MEMBER_TYPES,
  WORKSPACE_MEMBER_STATUSES,
  buildWorkspaceMemberRegistry,
  getWorkspaceMemberRegistry,
  workspaceMemberRegistryFingerprint,
  clearWorkspaceMemberRegistry,
  type WorkspaceMemberRegistry,
  type WorkspaceMemberType,
  type WorkspaceMemberStatus,
} from "./workspace-member-registry";

export {
  EP_2_WP3_ID,
  EP_WORKSPACE_ROLE_REGISTRY_BASELINE,
  EP_WORKSPACE_ROLE_REGISTRY_VERSION,
  WORKSPACE_ROLE_REGISTRY_CAPABILITY,
  WORKSPACE_ROLE_TYPES,
  WORKSPACE_ROLE_STATUSES,
  buildWorkspaceRoleRegistry,
  getWorkspaceRoleRegistry,
  workspaceRoleRegistryFingerprint,
  clearWorkspaceRoleRegistry,
  type WorkspaceRoleRegistry,
  type WorkspaceRoleType,
  type WorkspaceRoleStatus,
} from "./workspace-role-registry";

export {
  EP_2_WP4_ID,
  EP_WORKSPACE_PERMISSION_REGISTRY_BASELINE,
  EP_WORKSPACE_PERMISSION_REGISTRY_VERSION,
  WORKSPACE_PERMISSION_REGISTRY_CAPABILITY,
  WORKSPACE_PERMISSION_TYPES,
  WORKSPACE_PERMISSION_STATUSES,
  buildWorkspacePermissionRegistry,
  getWorkspacePermissionRegistry,
  workspacePermissionRegistryFingerprint,
  clearWorkspacePermissionRegistry,
  type WorkspacePermissionRegistry,
  type WorkspacePermissionType,
  type WorkspacePermissionStatus,
} from "./workspace-permission-registry";

export {
  EP_2_WP5_ID,
  EP_WORKSPACE_ACCESS_REGISTRY_BASELINE,
  EP_WORKSPACE_ACCESS_REGISTRY_VERSION,
  WORKSPACE_ACCESS_REGISTRY_CAPABILITY,
  WORKSPACE_ACCESS_TYPES,
  WORKSPACE_ACCESS_STATUSES,
  buildWorkspaceAccessRegistry,
  getWorkspaceAccessRegistry,
  workspaceAccessRegistryFingerprint,
  clearWorkspaceAccessRegistry,
  type WorkspaceAccessRegistry,
  type WorkspaceAccessType,
  type WorkspaceAccessStatus,
} from "./workspace-access-registry";

export {
  EP_2_WP6_ID,
  EP_WORKSPACE_SESSION_REGISTRY_BASELINE,
  EP_WORKSPACE_SESSION_REGISTRY_VERSION,
  WORKSPACE_SESSION_REGISTRY_CAPABILITY,
  WORKSPACE_SESSION_TYPES,
  WORKSPACE_SESSION_STATUSES,
  buildWorkspaceSessionRegistry,
  getWorkspaceSessionRegistry,
  workspaceSessionRegistryFingerprint,
  clearWorkspaceSessionRegistry,
  type WorkspaceSessionRegistry,
  type WorkspaceSessionType,
  type WorkspaceSessionStatus,
} from "./workspace-session-registry";

export {
  EP_2_WP7_ID,
  EP_WORKSPACE_EVENT_REGISTRY_BASELINE,
  EP_WORKSPACE_EVENT_REGISTRY_VERSION,
  WORKSPACE_EVENT_REGISTRY_CAPABILITY,
  WORKSPACE_EVENT_TYPES,
  WORKSPACE_EVENT_STATUSES,
  buildWorkspaceEventRegistry,
  getWorkspaceEventRegistry,
  workspaceEventRegistryFingerprint,
  clearWorkspaceEventRegistry,
  type WorkspaceEventRegistry,
  type WorkspaceEventType,
  type WorkspaceEventStatus,
} from "./workspace-event-registry";

export {
  EP_2_WP8_ID,
  EP_WORKSPACE_ACTIVITY_REGISTRY_BASELINE,
  EP_WORKSPACE_ACTIVITY_REGISTRY_VERSION,
  WORKSPACE_ACTIVITY_REGISTRY_CAPABILITY,
  WORKSPACE_ACTIVITY_TYPES,
  WORKSPACE_ACTIVITY_STATUSES,
  buildWorkspaceActivityRegistry,
  getWorkspaceActivityRegistry,
  workspaceActivityRegistryFingerprint,
  clearWorkspaceActivityRegistry,
  type WorkspaceActivityRegistry,
  type WorkspaceActivityType,
  type WorkspaceActivityStatus,
} from "./workspace-activity-registry";

export {
  EP_2_WP9_ID,
  EP_WORKSPACE_TASK_REGISTRY_BASELINE,
  EP_WORKSPACE_TASK_REGISTRY_VERSION,
  WORKSPACE_TASK_REGISTRY_CAPABILITY,
  WORKSPACE_TASK_TYPES,
  WORKSPACE_TASK_STATUSES,
  buildWorkspaceTaskRegistry,
  getWorkspaceTaskRegistry,
  workspaceTaskRegistryFingerprint,
  clearWorkspaceTaskRegistry,
  type WorkspaceTaskRegistry,
  type WorkspaceTaskType,
  type WorkspaceTaskStatus,
} from "./workspace-task-registry";

export {
  EP_2_WP10_ID,
  EP_WORKSPACE_QUEUE_REGISTRY_BASELINE,
  EP_WORKSPACE_QUEUE_REGISTRY_VERSION,
  WORKSPACE_QUEUE_REGISTRY_CAPABILITY,
  WORKSPACE_QUEUE_TYPES,
  WORKSPACE_QUEUE_STATUSES,
  buildWorkspaceQueueRegistry,
  getWorkspaceQueueRegistry,
  workspaceQueueRegistryFingerprint,
  clearWorkspaceQueueRegistry,
  type WorkspaceQueueRegistry,
  type WorkspaceQueueType,
  type WorkspaceQueueStatus,
} from "./workspace-queue-registry";

export {
  EP_2_WP11_ID,
  EP_WORKSPACE_ASSIGNMENT_REGISTRY_BASELINE,
  EP_WORKSPACE_ASSIGNMENT_REGISTRY_VERSION,
  WORKSPACE_ASSIGNMENT_REGISTRY_CAPABILITY,
  WORKSPACE_ASSIGNMENT_TYPES,
  WORKSPACE_ASSIGNMENT_STATUSES,
  buildWorkspaceAssignmentRegistry,
  getWorkspaceAssignmentRegistry,
  workspaceAssignmentRegistryFingerprint,
  clearWorkspaceAssignmentRegistry,
  type WorkspaceAssignmentRegistry,
  type WorkspaceAssignmentType,
  type WorkspaceAssignmentStatus,
} from "./workspace-assignment-registry";

export {
  EP_2_WP12_ID,
  EP_WORKSPACE_EXECUTION_REGISTRY_BASELINE,
  EP_WORKSPACE_EXECUTION_REGISTRY_VERSION,
  WORKSPACE_EXECUTION_REGISTRY_CAPABILITY,
  WORKSPACE_EXECUTION_TYPES,
  WORKSPACE_EXECUTION_STATUSES,
  buildWorkspaceExecutionRegistry,
  getWorkspaceExecutionRegistry,
  workspaceExecutionRegistryFingerprint,
  clearWorkspaceExecutionRegistry,
  type WorkspaceExecutionRegistry,
  type WorkspaceExecutionType,
  type WorkspaceExecutionStatus,
} from "./workspace-execution-registry";

export {
  EP_2_WP13_ID,
  EP_WORKSPACE_RESULT_REGISTRY_BASELINE,
  EP_WORKSPACE_RESULT_REGISTRY_VERSION,
  WORKSPACE_RESULT_REGISTRY_CAPABILITY,
  WORKSPACE_RESULT_TYPES,
  WORKSPACE_RESULT_STATUSES,
  buildWorkspaceResultRegistry,
  getWorkspaceResultRegistry,
  workspaceResultRegistryFingerprint,
  clearWorkspaceResultRegistry,
  type WorkspaceResultRegistry,
  type WorkspaceResultType,
  type WorkspaceResultStatus,
} from "./workspace-result-registry";

export {
  EP_2_WP14_ID,
  EP_WORKSPACE_SNAPSHOT_BASELINE,
  EP_WORKSPACE_SNAPSHOT_VERSION,
  WORKSPACE_SNAPSHOT_CAPABILITY,
  buildWorkspaceSnapshot,
  getWorkspaceSnapshot,
  workspaceSnapshotFingerprint,
  clearWorkspaceSnapshot,
  type WorkspaceSnapshot,
} from "./workspace-snapshot";

export {
  EP_2_WP15_ID,
  EP_WORKSPACE_QUERY_BASELINE,
  EP_WORKSPACE_QUERY_VERSION,
  WORKSPACE_QUERY_CAPABILITY,
  buildWorkspaceQuery,
  getWorkspaceQuery,
  workspaceQueryFingerprint,
  clearWorkspaceQuery,
  type WorkspaceQuery,
  type WorkspaceQueryCounts,
  type WorkspaceQueryTopItem,
} from "./workspace-query";

export {
  EP_2_WP16_ID,
  EP_2_FREEZE_VERSION,
  EP_2_CODENAME,
  EP_2_FREEZE_DATE,
  EP_2_BASELINE,
  EP_2_WORK_PACKAGES,
  EP_2_DEPENDENCY_CHAIN,
  EP_2_CORE_MODELS_UNCHANGED,
  buildEp2Manifest,
  computeEp2Fingerprint,
  listEp2ArtifactPresence,
  validateEp2DependencyChain,
  type Ep2Manifest,
  type Ep2WorkPackageEntry,
  type Ep2WorkPackageStatus,
} from "./ep2-manifest";

export {
  EP_3_ID,
  EP_3_WP1_ID,
  EP_COLLABORATION_CONTEXT_BASELINE,
  EP_COLLABORATION_CONTEXT_VERSION,
  COLLABORATION_CONTEXT_CAPABILITY,
  COLLABORATION_CONTEXT_STATUSES,
  buildCollaborationContext,
  getCollaborationContext,
  collaborationContextFingerprint,
  clearCollaborationContext,
  type CollaborationContext,
  type CollaborationContextStatus,
  type CollaborationParticipant,
  type CollaborationRoleRef,
  type CollaborationActivityRef,
  type CollaborationTaskRef,
} from "./collaboration-context";

export {
  EP_3_WP2_ID,
  EP_COLLABORATION_THREAD_REGISTRY_BASELINE,
  EP_COLLABORATION_THREAD_REGISTRY_VERSION,
  COLLABORATION_THREAD_REGISTRY_CAPABILITY,
  COLLABORATION_THREAD_TYPES,
  COLLABORATION_THREAD_STATUSES,
  buildCollaborationThreadRegistry,
  getCollaborationThreadRegistry,
  collaborationThreadRegistryFingerprint,
  clearCollaborationThreadRegistry,
  type CollaborationThreadRegistry,
  type CollaborationThreadType,
  type CollaborationThreadStatus,
} from "./collaboration-thread-registry";

export {
  EP_3_WP3_ID,
  EP_COLLABORATION_MESSAGE_REGISTRY_BASELINE,
  EP_COLLABORATION_MESSAGE_REGISTRY_VERSION,
  COLLABORATION_MESSAGE_REGISTRY_CAPABILITY,
  COLLABORATION_MESSAGE_TYPES,
  COLLABORATION_MESSAGE_STATUSES,
  buildCollaborationMessageRegistry,
  getCollaborationMessageRegistry,
  collaborationMessageRegistryFingerprint,
  clearCollaborationMessageRegistry,
  type CollaborationMessageRegistry,
  type CollaborationMessageType,
  type CollaborationMessageStatus,
} from "./collaboration-message-registry";

export {
  EP_3_WP4_ID,
  EP_COLLABORATION_REACTION_REGISTRY_BASELINE,
  EP_COLLABORATION_REACTION_REGISTRY_VERSION,
  COLLABORATION_REACTION_REGISTRY_CAPABILITY,
  COLLABORATION_REACTION_TYPES,
  COLLABORATION_REACTION_STATUSES,
  buildCollaborationReactionRegistry,
  getCollaborationReactionRegistry,
  collaborationReactionRegistryFingerprint,
  clearCollaborationReactionRegistry,
  type CollaborationReactionRegistry,
  type CollaborationReactionType,
  type CollaborationReactionStatus,
} from "./collaboration-reaction-registry";

export {
  EP_3_WP5_ID,
  EP_COLLABORATION_PRESENCE_REGISTRY_BASELINE,
  EP_COLLABORATION_PRESENCE_REGISTRY_VERSION,
  COLLABORATION_PRESENCE_REGISTRY_CAPABILITY,
  COLLABORATION_PRESENCE_TYPES,
  COLLABORATION_PRESENCE_STATUSES,
  buildCollaborationPresenceRegistry,
  getCollaborationPresenceRegistry,
  collaborationPresenceRegistryFingerprint,
  clearCollaborationPresenceRegistry,
  type CollaborationPresenceRegistry,
  type CollaborationPresenceType,
  type CollaborationPresenceStatus,
} from "./collaboration-presence-registry";

export {
  EP_3_WP6_ID,
  EP_COLLABORATION_STATUS_REGISTRY_BASELINE,
  EP_COLLABORATION_STATUS_REGISTRY_VERSION,
  COLLABORATION_STATUS_REGISTRY_CAPABILITY,
  COLLABORATION_STATUS_TYPES,
  COLLABORATION_STATUS_STATUSES,
  buildCollaborationStatusRegistry,
  getCollaborationStatusRegistry,
  collaborationStatusRegistryFingerprint,
  clearCollaborationStatusRegistry,
  type CollaborationStatusRegistry,
  type CollaborationStatusType,
  type CollaborationStatusRecordStatus,
} from "./collaboration-status-registry";

export {
  EP_3_WP7_ID,
  EP_COLLABORATION_SNAPSHOT_BASELINE,
  EP_COLLABORATION_SNAPSHOT_VERSION,
  COLLABORATION_SNAPSHOT_CAPABILITY,
  buildCollaborationSnapshot,
  getCollaborationSnapshot,
  collaborationSnapshotFingerprint,
  clearCollaborationSnapshot,
  type CollaborationSnapshot,
} from "./collaboration-snapshot";

export {
  EP_3_WP8_ID,
  EP_COLLABORATION_QUERY_BASELINE,
  EP_COLLABORATION_QUERY_VERSION,
  COLLABORATION_QUERY_CAPABILITY,
  buildCollaborationQuery,
  getCollaborationQuery,
  collaborationQueryFingerprint,
  clearCollaborationQuery,
  type CollaborationQuery,
  type CollaborationQueryCounts,
  type CollaborationQueryTopItem,
} from "./collaboration-query";

export {
  EP_3_WP9_ID,
  EP_3_FREEZE_VERSION,
  EP_3_CODENAME,
  EP_3_FREEZE_DATE,
  EP_3_BASELINE,
  EP_3_WORK_PACKAGES,
  EP_3_DEPENDENCY_CHAIN,
  EP_3_CORE_MODELS_UNCHANGED,
  buildEp3Manifest,
  computeEp3Fingerprint,
  listEp3ArtifactPresence,
  validateEp3DependencyChain,
  type Ep3Manifest,
  type Ep3WorkPackageEntry,
  type Ep3WorkPackageStatus,
} from "./ep3-manifest";

export {
  EP_4_ID,
  EP_4_WP1_ID,
  EP_WORKFLOW_CONTEXT_BASELINE,
  EP_WORKFLOW_CONTEXT_VERSION,
  WORKFLOW_CONTEXT_CAPABILITY,
  WORKFLOW_CONTEXT_STATUSES,
  buildWorkflowContext,
  getWorkflowContext,
  workflowContextFingerprint,
  clearWorkflowContext,
  type WorkflowContext,
  type WorkflowContextStatus,
  type WorkflowParticipant,
  type WorkflowTaskRef,
  type WorkflowAssignmentRef,
  type WorkflowActivityRef,
} from "./workflow-context";

export {
  EP_4_WP2_ID,
  EP_WORKFLOW_DEFINITION_BASELINE,
  EP_WORKFLOW_DEFINITION_VERSION,
  WORKFLOW_DEFINITION_CAPABILITY,
  WORKFLOW_SCENARIOS,
  WORKFLOW_TRIGGERS,
  WORKFLOW_ACTIONS,
  WORKFLOW_DEFINITION_STATUSES,
  buildWorkflowDefinition,
  getWorkflowDefinition,
  workflowDefinitionFingerprint,
  clearWorkflowDefinition,
  type WorkflowDefinition,
  type WorkflowScenario,
  type WorkflowTrigger,
  type WorkflowAction,
  type WorkflowDefinitionStatus,
} from "./workflow-definition";

export {
  EP_4_WP3_ID,
  EP_WORKFLOW_VIEW_BASELINE,
  EP_WORKFLOW_VIEW_VERSION,
  WORKFLOW_VIEW_CAPABILITY,
  buildWorkflowView,
  getWorkflowView,
  workflowViewFingerprint,
  clearWorkflowView,
  type WorkflowView,
  type WorkflowViewStatus,
} from "./workflow-view";

export {
  EP_4_WP4_ID,
  EP_WORKFLOW_API_BASELINE,
  EP_WORKFLOW_API_VERSION,
  WORKFLOW_API_CAPABILITY,
  WORKFLOW_API_METHODS,
  buildWorkflowApi,
  getWorkflowApi,
  workflowApiFingerprint,
  clearWorkflowApi,
  type WorkflowApi,
  type WorkflowApiMethod,
  type WorkflowApiStatus,
} from "./workflow-api";

export {
  EP_4_WP5_ID,
  EP_WORKFLOW_UI_CONTRACT_BASELINE,
  EP_WORKFLOW_UI_CONTRACT_VERSION,
  WORKFLOW_UI_CONTRACT_CAPABILITY,
  WORKFLOW_UI_COMPONENTS,
  buildWorkflowUiContract,
  getWorkflowUiContract,
  workflowUiContractFingerprint,
  clearWorkflowUiContract,
  type WorkflowUiContract,
  type WorkflowUiComponent,
  type WorkflowUiContractStatus,
} from "./workflow-ui-contract";

export {
  EP_4_WP6_ID,
  EP_WORKFLOW_EXECUTOR_BASELINE,
  EP_WORKFLOW_EXECUTOR_VERSION,
  WORKFLOW_EXECUTOR_CAPABILITY,
  WORKFLOW_HANDLERS,
  buildWorkflowExecutor,
  getWorkflowExecutor,
  workflowExecutorFingerprint,
  clearWorkflowExecutor,
  type WorkflowExecutor,
  type WorkflowHandler,
  type WorkflowExecutorStatus,
} from "./workflow-executor";

export {
  EP_4_WP7_ID,
  EP_WORKFLOW_INTEGRATION_BASELINE,
  EP_WORKFLOW_INTEGRATION_VERSION,
  WORKFLOW_INTEGRATION_CAPABILITY,
  buildWorkflowIntegration,
  getWorkflowIntegration,
  resolveWorkflowAppSurface,
  workflowIntegrationFingerprint,
  clearWorkflowIntegration,
  type WorkflowIntegration,
  type WorkflowAppSurface,
  type WorkflowIntegrationStatus,
} from "./workflow-integration";

export {
  EP_4_WP8_ID,
  EP_WORKFLOW_ENTRY_PANEL_BASELINE,
  EP_WORKFLOW_ENTRY_PANEL_VERSION,
  WORKFLOW_ENTRY_PANEL_CAPABILITY,
  buildWorkflowEntryPanel,
  getWorkflowEntryPanel,
  workflowEntryPanelFingerprint,
  clearWorkflowEntryPanel,
  type WorkflowEntryPanel,
  type WorkflowEntryPanelStatus,
} from "./workflow-entry-panel";

export {
  EP_4_WP9_ID,
  EP_WORKFLOW_PRODUCTION_UI_BASELINE,
  EP_WORKFLOW_PRODUCTION_UI_VERSION,
  WORKFLOW_PRODUCTION_UI_CAPABILITY,
  WORKFLOW_PRODUCTION_HOSTS,
  WORKFLOW_PRODUCTION_SURFACE_BY_SCENARIO,
  buildWorkflowProductionUi,
  getWorkflowProductionUi,
  getWorkflowProductionUiForHost,
  resolveWorkflowProductionSurface,
  workflowProductionUiFingerprint,
  clearWorkflowProductionUi,
  type WorkflowProductionHost,
  type WorkflowProductionSurfaceProof,
  type WorkflowProductionUiAction,
} from "./workflow-production-ui";

export {
  EP_4_WP10_ID,
  EP_WORKFLOW_E2E_BASELINE,
  EP_WORKFLOW_E2E_VERSION,
  WORKFLOW_E2E_CAPABILITY,
  WORKFLOW_E2E_ROUTES,
  WORKFLOW_E2E_HANDLERS,
  WORKFLOW_E2E_UI_COMPONENT,
  WORKFLOW_E2E_UI_COMPONENT_FILE,
  WORKFLOW_E2E_PAGE_FILES,
  buildWorkflowE2eVerification,
  getWorkflowE2eVerification,
  workflowE2eFingerprint,
  clearWorkflowE2eVerification,
  type WorkflowE2eRoute,
  type WorkflowE2eHandler,
  type WorkflowE2eCheckFlags,
  type WorkflowE2eSurface,
  type WorkflowE2eVerification,
} from "./workflow-e2e";

export {
  EP_4_WP11_ID,
  EP_4_FREEZE_VERSION,
  EP_4_CODENAME,
  EP_4_FREEZE_DATE,
  EP_4_BASELINE,
  EP_4_WORK_PACKAGES,
  EP_4_DEPENDENCY_CHAIN,
  EP_4_CORE_MODELS_UNCHANGED,
  EP_4_PRODUCTION_ROUTES,
  EP_4_PRODUCTION_HANDLERS,
  EP_4_PRODUCTION_UI_HOST,
  EP_4_PRODUCTION_PAGE_FILES,
  EP_4_PRODUCTION_UI_HOST_FILE,
  buildEp4Manifest,
  computeEp4Fingerprint,
  listEp4ArtifactPresence,
  validateEp4DependencyChain,
  type Ep4Manifest,
  type Ep4WorkPackageEntry,
  type Ep4WorkPackageStatus,
} from "./ep4-manifest";
