import type { RealEquipmentEntry } from "../shared/types";

export const REAL_EQUIPMENT_CATALOG: RealEquipmentEntry[] = [
  {
    sku: "TG-SKILLRUN-001",
    modelId: "equip-skillrun",
    modelName: "Skillrun",
    brandId: "brand-technogym",
    brandName: "Technogym",
    category: "cardio",
    subCategory: "Premium Treadmill",
    dimensionsCm: { length: 220, width: 95, height: 155 },
    weightKg: 220,
    powerRequirement: "220V / 20A",
    maxUserWeightKg: 180,
    connectivity: ["Bluetooth", "WiFi", "Mywellness Cloud", "RFID"],
    warrantyYears: 3,
    leadTimeDays: 45,
    procurementAvailability: "import-lead-time",
    datasheetRef: "DS-Technogym-Skillrun-v3.2",
    mode: "real-catalog",
  },
  {
    sku: "TG-SKILLBIKE-002",
    modelId: "equip-skillbike",
    modelName: "Technogym Skillbike",
    brandId: "brand-technogym",
    brandName: "Technogym",
    category: "group-training",
    subCategory: "Indoor Cycle",
    dimensionsCm: { length: 140, width: 60, height: 130 },
    weightKg: 65,
    powerRequirement: "220V / 10A",
    maxUserWeightKg: 150,
    connectivity: ["Bluetooth", "WiFi", "Mywellness Cloud"],
    warrantyYears: 3,
    leadTimeDays: 45,
    procurementAvailability: "import-lead-time",
    datasheetRef: "DS-Technogym-Skillbike-v2.1",
    mode: "real-catalog",
  },
  {
    sku: "TG-RECOVERY-R1",
    modelId: "equip-recovery-r1",
    modelName: "Recovery Station R1",
    brandId: "brand-technogym",
    brandName: "Technogym",
    category: "recovery",
    subCategory: "Stretch & Recovery",
    dimensionsCm: { length: 180, width: 80, height: 120 },
    weightKg: 85,
    powerRequirement: "N/A",
    maxUserWeightKg: 200,
    connectivity: [],
    warrantyYears: 3,
    leadTimeDays: 45,
    procurementAvailability: "import-lead-time",
    datasheetRef: "DS-Technogym-RecoveryR1-v1.0",
    mode: "real-catalog",
  },
  {
    sku: "LF-T5-001",
    modelId: "equip-t5-treadmill",
    modelName: "T5 Treadmill",
    brandId: "brand-life-fitness",
    brandName: "Life Fitness",
    category: "cardio",
    subCategory: "Commercial Treadmill",
    dimensionsCm: { length: 210, width: 90, height: 150 },
    weightKg: 195,
    powerRequirement: "220V / 15A",
    maxUserWeightKg: 180,
    connectivity: ["Bluetooth", "LF Connect"],
    warrantyYears: 3,
    leadTimeDays: 30,
    procurementAvailability: "in-stock",
    datasheetRef: "DS-LifeFitness-T5-v4.0",
    mode: "real-catalog",
  },
  {
    sku: "LF-SYNRGY360-001",
    modelId: "equip-synrgy360",
    modelName: "SYNRGY360",
    brandId: "brand-life-fitness",
    brandName: "Life Fitness",
    category: "functional",
    subCategory: "Functional Training System",
    dimensionsCm: { length: 360, width: 360, height: 240 },
    weightKg: 450,
    powerRequirement: "N/A",
    maxUserWeightKg: 200,
    connectivity: ["LF Connect"],
    warrantyYears: 3,
    leadTimeDays: 60,
    procurementAvailability: "made-to-order",
    datasheetRef: "DS-LifeFitness-SYNRGY360-v2.5",
    mode: "real-catalog",
  },
  {
    sku: "JH-A5700-001",
    modelId: "equip-johnson-a5700",
    modelName: "Johnson A5700",
    brandId: "brand-johnson",
    brandName: "Johnson",
    category: "strength",
    subCategory: "Selectorized Strength",
    dimensionsCm: { length: 160, width: 120, height: 200 },
    weightKg: 280,
    powerRequirement: "N/A",
    maxUserWeightKg: 150,
    connectivity: [],
    warrantyYears: 2,
    leadTimeDays: 21,
    procurementAvailability: "in-stock",
    datasheetRef: "DS-Johnson-A5700-v1.3",
    mode: "real-catalog",
  },
  {
    sku: "MX-SDRIVE-001",
    modelId: "equip-matrix-sdrive",
    modelName: "Matrix S-Drive",
    brandId: "brand-matrix",
    brandName: "Matrix",
    category: "cardio",
    subCategory: "Performance Trainer",
    dimensionsCm: { length: 200, width: 85, height: 145 },
    weightKg: 175,
    powerRequirement: "220V / 13A",
    maxUserWeightKg: 180,
    connectivity: ["Bluetooth", "Matrix Connect"],
    warrantyYears: 2,
    leadTimeDays: 28,
    procurementAvailability: "in-stock",
    datasheetRef: "DS-Matrix-SDrive-v2.0",
    mode: "real-catalog",
  },
  {
    sku: "SH-T8000-001",
    modelId: "equip-sh-t8000",
    modelName: "SH-T8000",
    brandId: "brand-shuhua",
    brandName: "Shuhua",
    category: "cardio",
    subCategory: "Commercial Treadmill",
    dimensionsCm: { length: 200, width: 85, height: 145 },
    weightKg: 160,
    powerRequirement: "220V / 10A",
    maxUserWeightKg: 150,
    connectivity: ["Basic Console"],
    warrantyYears: 2,
    leadTimeDays: 14,
    procurementAvailability: "in-stock",
    datasheetRef: "DS-Shuhua-T8000-v1.5",
    mode: "real-catalog",
  },
  {
    sku: "IP-IT7000-001",
    modelId: "equip-impulse-it7000",
    modelName: "Impulse IT7000",
    brandId: "brand-impulse",
    brandName: "Impulse",
    category: "strength",
    subCategory: "Multi-Station",
    dimensionsCm: { length: 250, width: 150, height: 220 },
    weightKg: 320,
    powerRequirement: "N/A",
    maxUserWeightKg: 150,
    connectivity: [],
    warrantyYears: 2,
    leadTimeDays: 14,
    procurementAvailability: "in-stock",
    datasheetRef: "DS-Impulse-IT7000-v1.2",
    mode: "real-catalog",
  },
  {
    sku: "IF-AIBIKE-001",
    modelId: "equip-ai-smart-bike",
    modelName: "AI Smart Bike Pro",
    brandId: "brand-intelligentfit",
    brandName: "IntelligentFit",
    category: "smart-connected",
    subCategory: "Connected Indoor Cycle",
    dimensionsCm: { length: 130, width: 55, height: 125 },
    weightKg: 55,
    powerRequirement: "220V / 5A",
    maxUserWeightKg: 150,
    connectivity: ["Bluetooth", "WiFi", "Cloud API", "Tender Intelligence SDK"],
    warrantyYears: 2,
    leadTimeDays: 10,
    procurementAvailability: "in-stock",
    datasheetRef: "DS-IntelligentFit-AIBikePro-v1.0",
    mode: "real-catalog",
  },
];

export function getRealEquipmentBySku(sku: string): RealEquipmentEntry | undefined {
  return REAL_EQUIPMENT_CATALOG.find((e) => e.sku === sku);
}

export function getRealEquipmentByBrand(brandName: string): RealEquipmentEntry[] {
  return REAL_EQUIPMENT_CATALOG.filter((e) => e.brandName === brandName);
}

export function getAllRealEquipment(): RealEquipmentEntry[] {
  return [...REAL_EQUIPMENT_CATALOG];
}
