import { WORKSPACE_QUOTE_RUNTIME_P5_META, WORKSPACE_QUOTE_RUNTIME_P5_TAG } from "./v55-p5-meta";

export const WORKSPACE_QUOTE_RUNTIME_P5_FREEZE = {
  tag: WORKSPACE_QUOTE_RUNTIME_P5_TAG,
  version: WORKSPACE_QUOTE_RUNTIME_P5_META.version,
  status: WORKSPACE_QUOTE_RUNTIME_P5_META.status,
  frozen: false,
  dependencyTag: WORKSPACE_QUOTE_RUNTIME_P5_META.dependencyTag,
  verifyChecks: WORKSPACE_QUOTE_RUNTIME_P5_META.verifyChecks,
  nextHorizon: WORKSPACE_QUOTE_RUNTIME_P5_META.nextHorizon,
  note: WORKSPACE_QUOTE_RUNTIME_P5_META.note,
} as const;
